/**
 * The gate was pointing the wrong way.
 *
 * nav-destinations.spec.ts asserts every nav href resolves to a page. Nothing
 * asserted the converse — that every page has a door. So the product accumulated
 * finished, tested, styled screens that no user could navigate to, and the nav
 * kept being repaired one entry at a time: 9857a397, 1ea8c4b7, 21f512d5,
 * b43a3d4c, 83588f95. Five consecutive commits treating a symptom.
 *
 * Measured here: 74 of 203 routes under /app are outside the nav — 36%.
 * Of those, 47 are real screens, several of them substantial: /app/finance/tax
 * (622 lines), /app/time-tracking (600), /app/crm/data-quality (560),
 * /app/finance/reconciliation (486). Work that produced zero user value and
 * carries full maintenance cost.
 *
 * Two of those doors were opened this week only because someone ran the app:
 * inventory sat behind a redirect to a commerce tab that did not exist, and
 * payments behind a permanent 308 into the same hole. Neither was findable by
 * reading source. This spec is the version that does not need a browser.
 *
 * WHY THE RULE IS BINARY
 * ---------------------
 * The first design had three arms: nav-reachable, OR linked from a reachable
 * page, OR allowlisted. The middle arm was measured and dropped. Navigation in
 * this app is 39 static <Link href="/app/…">, 222 dynamic href={…} and 293
 * router.push(…) — roughly 93% computed. A static link-graph would miss most
 * edges and report reachable screens as orphans, and a noisy gate gets disabled.
 * A disabled gate is worse than none.
 *
 * So: nav-reachable, or an explicit entry with a reason. No inference.
 *
 * REACHABILITY RULE
 * -----------------
 * A route is nav-reachable if the nav lands you in its subtree — the href equals
 * it, is a prefix of it, or it is a prefix of an href. /app/settings is reachable
 * because /app/settings/team is a nav item; /app/settings/billing is reachable
 * because /app/settings is. This is deliberately generous: the gate exists to
 * catch whole clusters with no way in, not to audit tab strips.
 *
 * THE ALLOWLIST IS THE BACKLOG
 * ----------------------------
 * Three reasons, and only three:
 *
 *   detail-route-of:<route>   a dynamic page reached from its parent record
 *   deliberately-unlinked     a redirect shim or re-export; a forwarding
 *                             address, not a destination
 *   todo-connect              a real screen with no door. THIS IS WORK, not an
 *                             exemption. 47 entries today; the number should
 *                             only go down.
 *
 * Adding a page without a nav entry now requires writing down which of those it
 * is, which is the whole point.
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

const WEB_SRC = path.join(__dirname, '..', '..');
const APP = path.join(WEB_SRC, 'app', 'app');

type Reason = `detail-route-of:${string}` | 'deliberately-unlinked' | 'todo-connect';

/**
 * Every /app route with no nav path to it, and why.
 *
 * Generated by measurement, not by hand — see the header. Sorted, so a diff
 * shows exactly which door opened or closed.
 */
const ORPHANED_BY_DESIGN: Record<string, Reason> = {
  "/app/accounting":                     'todo-connect',
  "/app/assets":                         'todo-connect',
  "/app/assets/[id]":                    'detail-route-of:/app/assets',
  "/app/automations":                    'todo-connect',
  "/app/blueprint":                      'deliberately-unlinked',
  "/app/briefing":                       'deliberately-unlinked',
  "/app/change-orders":                  'todo-connect',
  "/app/communicate/campaigns":          'deliberately-unlinked',
  "/app/continental-ops/delivery-notes": 'todo-connect',
  "/app/continental-ops/goods-receipts": 'todo-connect',
  "/app/continental-ops/receipts":       'todo-connect',
  "/app/continental-ops/stock-counts":   'todo-connect',
  "/app/control-tower":                  'deliberately-unlinked',
  "/app/crm/accounts":                   'todo-connect',
  "/app/crm/accounts/[accountId]":       'detail-route-of:/app/crm/accounts',
  "/app/crm/dashboard":                  'todo-connect',
  "/app/crm/data-quality":               'todo-connect',
  "/app/crm/duplicates":                 'todo-connect',
  "/app/crm/intake":                     'deliberately-unlinked',
  "/app/crm/network":                    'todo-connect',
  "/app/document-intelligence":          'todo-connect',
  "/app/documents":                      'deliberately-unlinked',
  "/app/documents/[instanceId]":         'detail-route-of:/app/documents',
  "/app/finance":                        'deliberately-unlinked',
  "/app/finance/accounting-periods":     'todo-connect',
  "/app/finance/accounts":               'deliberately-unlinked',
  "/app/finance/actions":                'todo-connect',
  "/app/finance/bank-rules":             'todo-connect',
  "/app/finance/cashflow":               'deliberately-unlinked',
  "/app/finance/credit-notes":           'todo-connect',
  "/app/finance/exchange-rates":         'todo-connect',
  "/app/finance/expenses":               'todo-connect',
  "/app/finance/fixed-assets":           'todo-connect',
  "/app/finance/journal":                'deliberately-unlinked',
  "/app/finance/ledger":                 'todo-connect',
  "/app/finance/reconciliation":         'todo-connect',
  "/app/finance/recurring-journals":     'todo-connect',
  "/app/finance/reports":                'todo-connect',
  "/app/finance/revenue":                'todo-connect',
  "/app/finance/settings":               'todo-connect',
  "/app/finance/tax":                    'todo-connect',
  "/app/finance/trial-balance":          'todo-connect',
  "/app/governance-flow":                'todo-connect',
  "/app/growth":                         'todo-connect',
  "/app/inbox":                          'deliberately-unlinked',
  "/app/inbox/intake":                   'todo-connect',
  "/app/key-flows":                      'todo-connect',
  "/app/key-flows/[rolekey]":            'detail-route-of:/app/key-flows',
  "/app/keyflow-command":                'deliberately-unlinked',
  "/app/marketing-flow":                 'todo-connect',
  "/app/money":                          'deliberately-unlinked',
  "/app/money/books":                    'deliberately-unlinked',
  "/app/money/expenses":                 'deliberately-unlinked',
  "/app/money/revenue":                  'deliberately-unlinked',
  "/app/onboarding":                     'todo-connect',
  "/app/onboarding/business-os":         'deliberately-unlinked',
  "/app/operations":                     'todo-connect',
  "/app/operations-flow":                'todo-connect',
  "/app/plans":                          'deliberately-unlinked',
  "/app/plans/[planId]":                 'detail-route-of:/app/plans',
  "/app/portal":                         'todo-connect',
  "/app/procurement":                    'todo-connect',
  "/app/procurement/[requestId]":        'detail-route-of:/app/procurement',
  "/app/procurement/new":                'todo-connect',
  "/app/procurement/suppliers":          'todo-connect',
  "/app/retainers":                      'todo-connect',
  "/app/sales-team":                     'todo-connect',
  "/app/schedule/calendar":              'deliberately-unlinked',
  "/app/storefront-intelligence":        'todo-connect',
  "/app/time-tracking":                  'todo-connect',
  "/app/trash":                          'todo-connect',
  "/app/whatsapp":                       'todo-connect',
  "/app/work/projects":                  'deliberately-unlinked',
  "/app/workflows":                      'deliberately-unlinked',
};

/** Every directory under app/app that renders a page. */
function routes(): string[] {
  const found: string[] = [];
  const walk = (dir: string, prefix: string) => {
    for (const entry of fs.readdirSync(dir)) {
      const full = path.join(dir, entry);
      if (!fs.statSync(full).isDirectory()) continue;
      const route = `${prefix}/${entry}`;
      if (fs.existsSync(path.join(full, 'page.tsx'))) found.push(route);
      walk(full, route);
    }
  };
  walk(APP, '/app');
  return found.sort();
}

function navHrefs(): string[] {
  const src = fs.readFileSync(path.join(WEB_SRC, 'lib', 'nav-config.ts'), 'utf8');
  return [...new Set([...src.matchAll(/href: "(\/app\/[^"]*)"/g)].map((m) => m[1].split('?')[0]))];
}

/** Does the nav land you anywhere in this route's subtree? */
function navReachable(route: string, hrefs: string[]): boolean {
  return hrefs.some(
    (h) =>
      route === h ||
      route.startsWith(h.replace(/\/$/, '') + '/') ||
      h.startsWith(route.replace(/\/$/, '') + '/'),
  );
}

describe('every screen has a door, or a written reason it does not', () => {
  const all = routes();
  const hrefs = navHrefs();

  it('finds both sides', () => {
    expect(all.length).toBeGreaterThan(150);
    expect(hrefs.length).toBeGreaterThan(30);
  });

  it('no page is unreachable and undeclared', () => {
    const undeclared = all.filter((r) => !navReachable(r, hrefs) && !ORPHANED_BY_DESIGN[r]);

    expect(
      undeclared,
      'these render a page that no nav path reaches, and say nothing about why. Add a nav ' +
        'entry, or an ORPHANED_BY_DESIGN entry saying whether it is a detail route, a ' +
        'deliberate shim, or work still to do',
    ).toEqual([]);
  });

  it('the allowlist names only routes that still exist', () => {
    // A stale exemption is where the next orphan hides — the same failure as
    // ConversationThread sitting in BUSINESS_ID_MODELS after the model was
    // dropped.
    const gone = Object.keys(ORPHANED_BY_DESIGN).filter((r) => !all.includes(r));

    expect(gone, `these no longer exist — remove them: ${gone.join(', ')}`).toEqual([]);
  });

  it('the allowlist does not exempt routes that are now in the nav', () => {
    // When a door opens, the entry has to go. Otherwise the backlog never
    // visibly shrinks and the list stops meaning anything.
    const nowReachable = Object.keys(ORPHANED_BY_DESIGN).filter((r) => navReachable(r, hrefs));

    expect(
      nowReachable,
      `these are reachable now — delete their entries: ${nowReachable.join(', ')}`,
    ).toEqual([]);
  });

  it('every detail-route-of points at a route that exists', () => {
    const dangling = Object.entries(ORPHANED_BY_DESIGN)
      .filter(([, why]) => why.startsWith('detail-route-of:'))
      .map(([r, why]) => [r, why.slice('detail-route-of:'.length)] as const)
      .filter(([, parent]) => !all.includes(parent));

    expect(dangling.map(([r, p]) => `${r} -> ${p}`), 'parent route is gone').toEqual([]);
  });

  it('the connect backlog does not grow', () => {
    // A ratchet. 47 is today's count; this fails if it rises, which makes
    // "ship a screen and wire it later" a decision someone has to argue for.
    const todo = Object.values(ORPHANED_BY_DESIGN).filter((w) => w === 'todo-connect');

    expect(
      todo.length,
      'more screens are now unreachable than when this gate was written. Connect one, or ' +
        'delete one, before adding another',
    ).toBeLessThanOrEqual(47);
  });
});
