import type { GenesisQuestion } from './business-genesis.types';

export const GENESIS_QUESTION_BANK: GenesisQuestion[] = [
  {
    id: 'founderProfile.founderName',
    section: 'founderProfile',
    field: 'founderName',
    label: 'What is your full name?',
    helper: 'This helps us personalise your founder profile and legal documents.',
    type: 'text',
    priority: 10,
  },
  {
    id: 'founderProfile.weeklyAvailabilityHours',
    section: 'founderProfile',
    field: 'weeklyAvailabilityHours',
    label: 'How many hours per week can you commit to this business?',
    helper: 'Be realistic — this affects pacing and automation recommendations.',
    type: 'number',
    priority: 8,
  },
  {
    id: 'legalProfile.hasPhysicalLocation',
    section: 'legalProfile',
    field: 'hasPhysicalLocation',
    label: 'Will the business have a physical location customers can visit?',
    type: 'boolean',
    priority: 9,
  },
  {
    id: 'ownershipProfile.hasPartners',
    section: 'ownershipProfile',
    field: 'hasPartners',
    label: 'Will you have co-founders or partners in this business?',
    type: 'boolean',
    priority: 9,
  },
  {
    id: 'registrationProfile.hasEmployees',
    section: 'registrationProfile',
    field: 'hasEmployees',
    label: 'Do you plan to hire employees (not contractors)?',
    type: 'boolean',
    priority: 9,
  },
  {
    id: 'taxProfile.estimatedAnnualRevenue',
    section: 'taxProfile',
    field: 'estimatedAnnualRevenue',
    label: 'What is your estimated annual revenue in the first year?',
    helper: 'A rough figure is fine. It drives tax and registration guidance.',
    type: 'currency',
    priority: 8,
  },
  {
    id: 'projectionProfile.monthlyFixedCosts',
    section: 'projectionProfile',
    field: 'monthlyFixedCosts',
    label: 'What are your expected monthly fixed costs?',
    helper: 'Rent, subscriptions, salaries, insurance, etc.',
    type: 'currency',
    priority: 8,
  },
  {
    id: 'projectionProfile.expectedMonthlyUnits',
    section: 'projectionProfile',
    field: 'expectedMonthlyUnits',
    label: 'How many units (sales, bookings, clients) do you expect per month?',
    type: 'number',
    priority: 7,
  },
  {
    id: 'customerModel.idealCustomer',
    section: 'customerModel',
    field: 'idealCustomer',
    label: 'Describe your ideal customer in one or two sentences.',
    type: 'textarea',
    priority: 7,
  },
  {
    id: 'salesSystem.salesChannels',
    section: 'salesSystem',
    field: 'salesChannels',
    label: 'Which sales channels will you use?',
    type: 'multi_select',
    options: [
      'Online store / website',
      'Social media / DMs',
      'In-person / walk-in',
      'Phone / WhatsApp',
      'Email',
      'Referrals / word of mouth',
      'Marketplaces / platforms',
    ],
    priority: 6,
  },
];
