/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║                         NOTION CONNECTOR                                  ║
 * ║        Read, create, and update pages, databases, and blocks             ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */

import { ExternalConnectorDefinition } from '../key-cortex-external-connector.types';

export const NotionConnector: ExternalConnectorDefinition = {
  id: 'notion',
  name: 'Notion',
  description: 'Read, create, and update pages, databases, and blocks in Notion workspaces',
  category: 'productivity',
  authType: 'api_key',
  logoUrl: 'https://cdn.keyflow.io/connectors/notion.svg',
  website: 'https://notion.so',
  docsUrl: 'https://developers.notion.com/reference',
  baseUrl: 'https://api.notion.com/v1',
  supportsOAuth: true,
  oauthScopes: [],
  defaultHeaders: {
    'Content-Type': 'application/json',
    'Notion-Version': '2022-06-28',
  },
  rateLimit: {
    requestsPerWindow: 300,
    windowSeconds: 60,
    burstLimit: 30,
  },

  configSchema: [
    {
      name: 'integrationToken',
      type: 'password',
      label: 'Integration Token',
      description: 'Notion internal integration token (starts with secret_)',
      required: true,
      placeholder: 'secret_...your_integration_token...',
      secret: true,
    },
    {
      name: 'oauthClientId',
      type: 'string',
      label: 'OAuth Client ID',
      description: 'OAuth client ID for public integrations',
      required: false,
      placeholder: 'your-oauth-client-id',
    },
    {
      name: 'oauthClientSecret',
      type: 'password',
      label: 'OAuth Client Secret',
      description: 'OAuth client secret for public integrations',
      required: false,
      placeholder: 'your-oauth-client-secret',
      secret: true,
    },
    {
      name: 'notionVersion',
      type: 'select',
      label: 'API Version',
      description: 'Notion API version',
      required: true,
      defaultValue: '2022-06-28',
      options: [
        { label: '2022-06-28', value: '2022-06-28' },
        { label: '2022-02-22', value: '2022-02-22' },
      ],
    },
    {
      name: 'defaultPageId',
      type: 'string',
      label: 'Default Page ID',
      description: 'Default parent page ID for new pages (32-char hex, no dashes)',
      required: false,
      placeholder: 'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6',
      validationPattern: '^[a-f0-9]{32}$',
    },
  ],

  actions: [
    {
      name: 'get_pages',
      description: 'Search for pages in the workspace',
      endpoint: '/search',
      method: 'POST',
      category: 'pages',
      parameters: [
        {
          name: 'query',
          type: 'string',
          label: 'Search Query',
          description: 'Text to search for in page titles',
          required: false,
          inBody: true,
        },
        {
          name: 'filter',
          type: 'json',
          label: 'Filter',
          description: 'Filter object: {value: "page", property: "object"}',
          required: false,
          inBody: true,
        },
        {
          name: 'sort',
          type: 'json',
          label: 'Sort',
          description: 'Sort object: {direction: "ascending", timestamp: "last_edited_time"}',
          required: false,
          inBody: true,
        },
        {
          name: 'page_size',
          type: 'number',
          label: 'Page Size',
          description: 'Number of results per page (max 100)',
          required: false,
          defaultValue: 10,
          inBody: true,
        },
        {
          name: 'start_cursor',
          type: 'string',
          label: 'Start Cursor',
          description: 'Pagination cursor',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.results[*].id, $.results[*].object, $.results[*].url, $.has_more, $.next_cursor',
    },
    {
      name: 'get_page',
      description: 'Retrieve a single page by ID',
      endpoint: '/pages/{page_id}',
      method: 'GET',
      category: 'pages',
      parameters: [
        {
          name: 'page_id',
          type: 'string',
          label: 'Page ID',
          description: 'ID of the page to retrieve',
          required: true,
          inPath: true,
        },
      ],
      returns: '$.id, $.object, $.url, $.properties.title, $.created_time, $.last_edited_time',
    },
    {
      name: 'create_page',
      description: 'Create a new page in Notion',
      endpoint: '/pages',
      method: 'POST',
      category: 'pages',
      parameters: [
        {
          name: 'parent',
          type: 'json',
          label: 'Parent',
          description: 'Parent database_id or page_id',
          required: true,
          inBody: true,
        },
        {
          name: 'properties',
          type: 'json',
          label: 'Properties',
          description: 'Page properties (title, etc.)',
          required: true,
          inBody: true,
        },
        {
          name: 'children',
          type: 'json',
          label: 'Content Blocks',
          description: 'Array of content block objects for page body',
          required: false,
          inBody: true,
        },
        {
          name: 'icon',
          type: 'json',
          label: 'Icon',
          description: 'Page icon (emoji or external file)',
          required: false,
          inBody: true,
        },
        {
          name: 'cover',
          type: 'json',
          label: 'Cover',
          description: 'Page cover image',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.id, $.object, $.url, $.properties, $.created_time',
      examplePayload: {
        parent: { page_id: 'a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6' },
        properties: {
          title: {
            title: [{ text: { content: 'My New Page' } }],
          },
        },
        children: [
          {
            object: 'block',
            type: 'paragraph',
            paragraph: {
              rich_text: [{ type: 'text', text: { content: 'Hello from KeyFlowOS!' } }],
            },
          },
        ],
        icon: { emoji: '📄' },
      },
    },
    {
      name: 'update_page',
      description: 'Update page properties',
      endpoint: '/pages/{page_id}',
      method: 'PATCH',
      category: 'pages',
      parameters: [
        {
          name: 'page_id',
          type: 'string',
          label: 'Page ID',
          description: 'ID of the page to update',
          required: true,
          inPath: true,
        },
        {
          name: 'properties',
          type: 'json',
          label: 'Properties',
          description: 'Updated page properties',
          required: true,
          inBody: true,
        },
        {
          name: 'archived',
          type: 'boolean',
          label: 'Archived',
          description: 'Archive or unarchive the page',
          required: false,
          inBody: true,
        },
        {
          name: 'icon',
          type: 'json',
          label: 'Icon',
          description: 'Updated page icon',
          required: false,
          inBody: true,
        },
        {
          name: 'cover',
          type: 'json',
          label: 'Cover',
          description: 'Updated page cover',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.id, $.object, $.url, $.properties, $.last_edited_time',
      examplePayload: {
        properties: {
          title: {
            title: [{ text: { content: 'Updated Page Title' } }],
          },
        },
        archived: false,
      },
    },
    {
      name: 'get_databases',
      description: 'Search for databases in the workspace',
      endpoint: '/search',
      method: 'POST',
      category: 'databases',
      parameters: [
        {
          name: 'query',
          type: 'string',
          label: 'Search Query',
          description: 'Text to search for in database titles',
          required: false,
          inBody: true,
        },
        {
          name: 'filter',
          type: 'json',
          label: 'Filter',
          description: 'Filter object: {value: "database", property: "object"}',
          required: false,
          inBody: true,
        },
        {
          name: 'sort',
          type: 'json',
          label: 'Sort',
          description: 'Sort object',
          required: false,
          inBody: true,
        },
        {
          name: 'page_size',
          type: 'number',
          label: 'Page Size',
          description: 'Number of results per page (max 100)',
          required: false,
          defaultValue: 10,
          inBody: true,
        },
        {
          name: 'start_cursor',
          type: 'string',
          label: 'Start Cursor',
          description: 'Pagination cursor',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.results[*].id, $.results[*].title, $.results[*].properties, $.has_more',
    },
    {
      name: 'get_database',
      description: 'Retrieve a database by ID',
      endpoint: '/databases/{database_id}',
      method: 'GET',
      category: 'databases',
      parameters: [
        {
          name: 'database_id',
          type: 'string',
          label: 'Database ID',
          description: 'ID of the database to retrieve',
          required: true,
          inPath: true,
        },
      ],
      returns: '$.id, $.title, $.properties, $.created_time, $.last_edited_time',
    },
    {
      name: 'query_database',
      description: 'Query entries from a database with optional filters',
      endpoint: '/databases/{database_id}/query',
      method: 'POST',
      category: 'databases',
      parameters: [
        {
          name: 'database_id',
          type: 'string',
          label: 'Database ID',
          description: 'ID of the database to query',
          required: true,
          inPath: true,
        },
        {
          name: 'filter',
          type: 'json',
          label: 'Filter',
          description: 'Database query filter object',
          required: false,
          inBody: true,
        },
        {
          name: 'sorts',
          type: 'json',
          label: 'Sorts',
          description: 'Array of sort objects',
          required: false,
          inBody: true,
        },
        {
          name: 'page_size',
          type: 'number',
          label: 'Page Size',
          description: 'Number of results per page (max 100)',
          required: false,
          defaultValue: 10,
          inBody: true,
        },
        {
          name: 'start_cursor',
          type: 'string',
          label: 'Start Cursor',
          description: 'Pagination cursor',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.results[*].id, $.results[*].properties, $.has_more, $.next_cursor',
      examplePayload: {
        filter: {
          property: 'Status',
          select: { equals: 'In Progress' },
        },
        sorts: [
          {
            property: 'Due date',
            direction: 'ascending',
          },
        ],
        page_size: 25,
      },
    },
    {
      name: 'create_database_entry',
      description: 'Create a new entry in a database',
      endpoint: '/pages',
      method: 'POST',
      category: 'databases',
      parameters: [
        {
          name: 'parent',
          type: 'json',
          label: 'Parent (Database)',
          description: '{database_id: "..."}',
          required: true,
          inBody: true,
        },
        {
          name: 'properties',
          type: 'json',
          label: 'Properties',
          description: 'Database entry properties matching the database schema',
          required: true,
          inBody: true,
        },
        {
          name: 'children',
          type: 'json',
          label: 'Content Blocks',
          description: 'Page content blocks',
          required: false,
          inBody: true,
        },
        {
          name: 'icon',
          type: 'json',
          label: 'Icon',
          description: 'Entry icon',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.id, $.object, $.url, $.properties, $.created_time',
      examplePayload: {
        parent: { database_id: 'a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6' },
        properties: {
          Name: {
            title: [{ text: { content: 'New Task' } }],
          },
          Status: {
            select: { name: 'To Do' },
          },
        },
        icon: { emoji: '✅' },
      },
    },
    {
      name: 'update_database_entry',
      description: 'Update an existing database entry',
      endpoint: '/pages/{page_id}',
      method: 'PATCH',
      category: 'databases',
      parameters: [
        {
          name: 'page_id',
          type: 'string',
          label: 'Page/Entry ID',
          description: 'ID of the database entry to update',
          required: true,
          inPath: true,
        },
        {
          name: 'properties',
          type: 'json',
          label: 'Properties',
          description: 'Updated properties',
          required: true,
          inBody: true,
        },
        {
          name: 'archived',
          type: 'boolean',
          label: 'Archived',
          description: 'Archive the entry',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.id, $.object, $.properties, $.last_edited_time',
    },
    {
      name: 'get_page_blocks',
      description: 'Retrieve the content blocks of a page',
      endpoint: '/blocks/{block_id}/children',
      method: 'GET',
      category: 'blocks',
      parameters: [
        {
          name: 'block_id',
          type: 'string',
          label: 'Block/Page ID',
          description: 'ID of the page or block to get children of',
          required: true,
          inPath: true,
        },
        {
          name: 'page_size',
          type: 'number',
          label: 'Page Size',
          description: 'Number of blocks per page (max 100)',
          required: false,
          defaultValue: 100,
          inQuery: true,
        },
        {
          name: 'start_cursor',
          type: 'string',
          label: 'Start Cursor',
          description: 'Pagination cursor',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.results[*].id, $.results[*].type, $.results[*][$.results[*].type], $.has_more, $.next_cursor',
    },
    {
      name: 'append_blocks',
      description: 'Append content blocks to a page or block',
      endpoint: '/blocks/{block_id}/children',
      method: 'PATCH',
      category: 'blocks',
      parameters: [
        {
          name: 'block_id',
          type: 'string',
          label: 'Block/Page ID',
          description: 'ID of the page or block to append to',
          required: true,
          inPath: true,
        },
        {
          name: 'children',
          type: 'json',
          label: 'Children',
          description: 'Array of block objects to append',
          required: true,
          inBody: true,
        },
        {
          name: 'after',
          type: 'string',
          label: 'After Block ID',
          description: 'Block ID to append after (for positioning)',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.results[*].id, $.results[*].type, $.results[*].created_time',
      examplePayload: {
        children: [
          {
            object: 'block',
            type: 'heading_2',
            heading_2: {
              rich_text: [{ type: 'text', text: { content: 'Section Header' } }],
            },
          },
          {
            object: 'block',
            type: 'paragraph',
            paragraph: {
              rich_text: [{ type: 'text', text: { content: 'Paragraph content here.' } }],
            },
          },
          {
            object: 'block',
            type: 'to_do',
            to_do: {
              rich_text: [{ type: 'text', text: { content: 'Check me off' } }],
              checked: false,
            },
          },
        ],
      },
    },
    {
      name: 'archive_page',
      description: 'Archive (soft-delete) a page',
      endpoint: '/pages/{page_id}',
      method: 'PATCH',
      category: 'pages',
      parameters: [
        {
          name: 'page_id',
          type: 'string',
          label: 'Page ID',
          description: 'ID of the page to archive',
          required: true,
          inPath: true,
        },
      ],
      returns: '$.id, $.archived: true',
    },
    {
      name: 'get_users',
      description: 'List users in the workspace',
      endpoint: '/users',
      method: 'GET',
      category: 'workspace',
      parameters: [
        {
          name: 'page_size',
          type: 'number',
          label: 'Page Size',
          description: 'Number of users per page (max 100)',
          required: false,
          defaultValue: 100,
          inQuery: true,
        },
        {
          name: 'start_cursor',
          type: 'string',
          label: 'Start Cursor',
          description: 'Pagination cursor',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.results[*].id, $.results[*].name, $.results[*].type, $.results[*].person.email?',
    },
  ],

  triggers: [
    {
      name: 'page_created',
      description: 'Triggered when a new page is created (via webhook)',
      eventType: 'page.created',
      payloadSchema: {
        id: 'string',
        object: 'string',
        created_time: 'string',
        last_edited_time: 'string',
        created_by: 'object',
        parent: 'object',
        url: 'string',
        properties: 'object',
      },
      examplePayload: {
        id: 'a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6',
        object: 'page',
        created_time: '2024-01-15T10:30:00.000Z',
        last_edited_time: '2024-01-15T10:30:00.000Z',
        created_by: { id: 'user-id', object: 'user' },
        parent: { type: 'page_id', page_id: 'parent-page-id' },
        url: 'https://www.notion.so/Page-Title-a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6',
        properties: {},
      },
    },
    {
      name: 'page_updated',
      description: 'Triggered when a page is updated',
      eventType: 'page.updated',
      payloadSchema: {
        id: 'string',
        object: 'string',
        last_edited_time: 'string',
        last_edited_by: 'object',
        url: 'string',
        properties: 'object',
      },
    },
    {
      name: 'database_entry_created',
      description: 'Triggered when a database entry is created',
      eventType: 'database_entry.created',
      payloadSchema: {
        id: 'string',
        object: 'string',
        created_time: 'string',
        parent: 'object',
        url: 'string',
        properties: 'object',
      },
    },
    {
      name: 'database_entry_updated',
      description: 'Triggered when a database entry is updated',
      eventType: 'database_entry.updated',
      payloadSchema: {
        id: 'string',
        object: 'string',
        last_edited_time: 'string',
        parent: 'object',
        url: 'string',
        properties: 'object',
      },
    },
  ],
};
