/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║                       SALESFORCE CONNECTOR                                ║
 * ║       Manage leads, contacts, opportunities, and tasks                   ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */

import { ExternalConnectorDefinition } from '../key-cortex-external-connector.types';

export const SalesforceConnector: ExternalConnectorDefinition = {
  id: 'salesforce',
  name: 'Salesforce',
  description: 'Manage leads, contacts, opportunities, and tasks in Salesforce CRM',
  category: 'crm',
  authType: 'oauth2',
  logoUrl: 'https://cdn.keyflow.io/connectors/salesforce.svg',
  website: 'https://salesforce.com',
  docsUrl: 'https://developer.salesforce.com/docs',
  baseUrl: 'https://{instance}.salesforce.com',
  supportsOAuth: true,
  oauthScopes: [
    'api',
    'refresh_token',
    'full',
    'chatter_api',
  ],
  defaultHeaders: {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
  },
  rateLimit: {
    requestsPerWindow: 100,
    windowSeconds: 60,
    burstLimit: 20,
  },

  configSchema: [
    {
      name: 'instanceUrl',
      type: 'url',
      label: 'Instance URL',
      description: 'Your Salesforce instance URL (e.g., https://mycompany.my.salesforce.com)',
      required: true,
      placeholder: 'https://mycompany.my.salesforce.com',
    },
    {
      name: 'clientId',
      type: 'string',
      label: 'Consumer Key (Client ID)',
      description: 'Connected App Consumer Key',
      required: true,
      placeholder: '3MVG9...',
    },
    {
      name: 'clientSecret',
      type: 'password',
      label: 'Consumer Secret (Client Secret)',
      description: 'Connected App Consumer Secret',
      required: true,
      placeholder: '...',
      secret: true,
    },
    {
      name: 'username',
      type: 'string',
      label: 'Username',
      description: 'Salesforce username for authentication',
      required: false,
      placeholder: 'admin@company.com',
    },
    {
      name: 'password',
      type: 'password',
      label: 'Password',
      description: 'Salesforce password (with security token appended)',
      required: false,
      placeholder: 'passwordSECURITYTOKEN',
      secret: true,
    },
    {
      name: 'securityToken',
      type: 'password',
      label: 'Security Token',
      description: 'Salesforce security token',
      required: false,
      placeholder: 'xxxxxxxxxxxx',
      secret: true,
    },
    {
      name: 'apiVersion',
      type: 'select',
      label: 'API Version',
      description: 'Salesforce API version',
      required: true,
      defaultValue: 'v59.0',
      options: [
        { label: 'v58.0 (Winter 24)', value: 'v58.0' },
        { label: 'v59.0 (Spring 24)', value: 'v59.0' },
        { label: 'v60.0 (Summer 24)', value: 'v60.0' },
        { label: 'v61.0 (Winter 25)', value: 'v61.0' },
        { label: 'v62.0 (Spring 25)', value: 'v62.0' },
      ],
    },
  ],

  actions: [
    {
      name: 'get_leads',
      description: 'Query leads from Salesforce',
      endpoint: '/services/data/{apiVersion}/query',
      method: 'GET',
      category: 'leads',
      parameters: [
        {
          name: 'apiVersion',
          type: 'string',
          label: 'API Version',
          description: 'Salesforce API version',
          required: false,
          defaultValue: 'v59.0',
          inPath: true,
        },
        {
          name: 'q',
          type: 'string',
          label: 'SOQL Query',
          description: 'SOQL query string (overrides other filters)',
          required: false,
          inQuery: true,
        },
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Maximum number of leads to return',
          required: false,
          defaultValue: 50,
          inQuery: true,
        },
        {
          name: 'fields',
          type: 'string',
          label: 'Fields',
          description: 'Comma-separated fields to select (default: Id, FirstName, LastName, Email, Company, Status)',
          required: false,
          defaultValue: 'Id,FirstName,LastName,Email,Company,Status,CreatedDate',
          inQuery: true,
        },
        {
          name: 'where',
          type: 'string',
          label: 'WHERE Clause',
          description: 'SOQL WHERE clause (without the WHERE keyword)',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.records[*].Id, $.records[*].FirstName, $.records[*].LastName, $.records[*].Email, $.records[*].Company, $.totalSize',
    },
    {
      name: 'create_lead',
      description: 'Create a new lead in Salesforce',
      endpoint: '/services/data/{apiVersion}/sobjects/Lead',
      method: 'POST',
      category: 'leads',
      parameters: [
        {
          name: 'apiVersion',
          type: 'string',
          label: 'API Version',
          description: 'Salesforce API version',
          required: false,
          defaultValue: 'v59.0',
          inPath: true,
        },
        {
          name: 'FirstName',
          type: 'string',
          label: 'First Name',
          description: 'Lead first name',
          required: false,
          inBody: true,
        },
        {
          name: 'LastName',
          type: 'string',
          label: 'Last Name',
          description: 'Lead last name',
          required: true,
          inBody: true,
        },
        {
          name: 'Email',
          type: 'string',
          label: 'Email',
          description: 'Lead email address',
          required: false,
          inBody: true,
        },
        {
          name: 'Company',
          type: 'string',
          label: 'Company',
          description: 'Lead company name',
          required: true,
          inBody: true,
        },
        {
          name: 'Phone',
          type: 'string',
          label: 'Phone',
          description: 'Lead phone number',
          required: false,
          inBody: true,
        },
        {
          name: 'Status',
          type: 'string',
          label: 'Status',
          description: 'Lead status',
          required: false,
          defaultValue: 'Open - Not Contacted',
          inBody: true,
          options: [
            { label: 'Open - Not Contacted', value: 'Open - Not Contacted' },
            { label: 'Working - Contacted', value: 'Working - Contacted' },
            { label: 'Closed - Converted', value: 'Closed - Converted' },
            { label: 'Closed - Not Converted', value: 'Closed - Not Converted' },
          ],
        },
        {
          name: 'LeadSource',
          type: 'string',
          label: 'Lead Source',
          description: 'Source of the lead',
          required: false,
          inBody: true,
        },
        {
          name: 'Description',
          type: 'textarea',
          label: 'Description',
          description: 'Lead description',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.id, $.success, $.errors',
      examplePayload: {
        FirstName: 'John',
        LastName: 'Doe',
        Email: 'john.doe@example.com',
        Company: 'Acme Inc',
        Status: 'Open - Not Contacted',
      },
    },
    {
      name: 'update_opportunity',
      description: 'Update an existing opportunity',
      endpoint: '/services/data/{apiVersion}/sobjects/Opportunity/{id}',
      method: 'PATCH',
      category: 'opportunities',
      parameters: [
        {
          name: 'apiVersion',
          type: 'string',
          label: 'API Version',
          description: 'Salesforce API version',
          required: false,
          defaultValue: 'v59.0',
          inPath: true,
        },
        {
          name: 'id',
          type: 'string',
          label: 'Opportunity ID',
          description: 'ID of the opportunity to update',
          required: true,
          inPath: true,
        },
        {
          name: 'Name',
          type: 'string',
          label: 'Name',
          description: 'Opportunity name',
          required: false,
          inBody: true,
        },
        {
          name: 'StageName',
          type: 'string',
          label: 'Stage',
          description: 'Sales stage',
          required: false,
          inBody: true,
          options: [
            { label: 'Prospecting', value: 'Prospecting' },
            { label: 'Qualification', value: 'Qualification' },
            { label: 'Needs Analysis', value: 'Needs Analysis' },
            { label: 'Value Proposition', value: 'Value Proposition' },
            { label: 'Id. Decision Makers', value: 'Id. Decision Makers' },
            { label: 'Perception Analysis', value: 'Perception Analysis' },
            { label: 'Proposal/Price Quote', value: 'Proposal/Price Quote' },
            { label: 'Negotiation/Review', value: 'Negotiation/Review' },
            { label: 'Closed Won', value: 'Closed Won' },
            { label: 'Closed Lost', value: 'Closed Lost' },
          ],
        },
        {
          name: 'Amount',
          type: 'number',
          label: 'Amount',
          description: 'Opportunity amount',
          required: false,
          inBody: true,
        },
        {
          name: 'CloseDate',
          type: 'string',
          label: 'Close Date',
          description: 'Expected close date (YYYY-MM-DD)',
          required: false,
          inBody: true,
        },
        {
          name: 'Probability',
          type: 'number',
          label: 'Probability',
          description: 'Probability of closing (0-100)',
          required: false,
          inBody: true,
        },
        {
          name: 'Description',
          type: 'textarea',
          label: 'Description',
          description: 'Opportunity description',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.id, $.success, $.errors',
    },
    {
      name: 'get_contacts',
      description: 'Query contacts from Salesforce',
      endpoint: '/services/data/{apiVersion}/query',
      method: 'GET',
      category: 'contacts',
      parameters: [
        {
          name: 'apiVersion',
          type: 'string',
          label: 'API Version',
          description: 'Salesforce API version',
          required: false,
          defaultValue: 'v59.0',
          inPath: true,
        },
        {
          name: 'q',
          type: 'string',
          label: 'SOQL Query',
          description: 'Custom SOQL query (overrides other params)',
          required: false,
          inQuery: true,
        },
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Maximum number of contacts',
          required: false,
          defaultValue: 50,
          inQuery: true,
        },
        {
          name: 'fields',
          type: 'string',
          label: 'Fields',
          description: 'Comma-separated fields',
          required: false,
          defaultValue: 'Id,FirstName,LastName,Email,Phone,AccountId,CreatedDate',
          inQuery: true,
        },
        {
          name: 'where',
          type: 'string',
          label: 'WHERE Clause',
          description: 'SOQL WHERE condition',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.records[*].Id, $.records[*].FirstName, $.records[*].LastName, $.records[*].Email, $.totalSize',
    },
    {
      name: 'create_task',
      description: 'Create a new task in Salesforce',
      endpoint: '/services/data/{apiVersion}/sobjects/Task',
      method: 'POST',
      category: 'tasks',
      parameters: [
        {
          name: 'apiVersion',
          type: 'string',
          label: 'API Version',
          description: 'Salesforce API version',
          required: false,
          defaultValue: 'v59.0',
          inPath: true,
        },
        {
          name: 'Subject',
          type: 'string',
          label: 'Subject',
          description: 'Task subject line',
          required: true,
          inBody: true,
        },
        {
          name: 'Status',
          type: 'string',
          label: 'Status',
          description: 'Task status',
          required: false,
          defaultValue: 'Not Started',
          inBody: true,
          options: [
            { label: 'Not Started', value: 'Not Started' },
            { label: 'In Progress', value: 'In Progress' },
            { label: 'Completed', value: 'Completed' },
            { label: 'Waiting on someone else', value: 'Waiting on someone else' },
            { label: 'Deferred', value: 'Deferred' },
          ],
        },
        {
          name: 'Priority',
          type: 'string',
          label: 'Priority',
          description: 'Task priority',
          required: false,
          defaultValue: 'Normal',
          inBody: true,
          options: [
            { label: 'High', value: 'High' },
            { label: 'Normal', value: 'Normal' },
            { label: 'Low', value: 'Low' },
          ],
        },
        {
          name: 'ActivityDate',
          type: 'string',
          label: 'Due Date',
          description: 'Task due date (YYYY-MM-DD)',
          required: false,
          inBody: true,
        },
        {
          name: 'Description',
          type: 'textarea',
          label: 'Description',
          description: 'Task description/comments',
          required: false,
          inBody: true,
        },
        {
          name: 'WhoId',
          type: 'string',
          label: 'Who ID',
          description: 'Related contact or lead ID',
          required: false,
          inBody: true,
        },
        {
          name: 'WhatId',
          type: 'string',
          label: 'What ID',
          description: 'Related account, opportunity, or custom object ID',
          required: false,
          inBody: true,
        },
        {
          name: 'OwnerId',
          type: 'string',
          label: 'Owner ID',
          description: 'Assigned user ID',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.id, $.success, $.errors',
    },
    {
      name: 'get_opportunities',
      description: 'Query opportunities from Salesforce',
      endpoint: '/services/data/{apiVersion}/query',
      method: 'GET',
      category: 'opportunities',
      parameters: [
        {
          name: 'apiVersion',
          type: 'string',
          label: 'API Version',
          description: 'Salesforce API version',
          required: false,
          defaultValue: 'v59.0',
          inPath: true,
        },
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Maximum number of opportunities',
          required: false,
          defaultValue: 50,
          inQuery: true,
        },
        {
          name: 'fields',
          type: 'string',
          label: 'Fields',
          description: 'Comma-separated fields to select',
          required: false,
          defaultValue: 'Id,Name,StageName,Amount,Probability,CloseDate,AccountId,CreatedDate',
          inQuery: true,
        },
        {
          name: 'where',
          type: 'string',
          label: 'WHERE Clause',
          description: 'SOQL WHERE condition',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.records[*].Id, $.records[*].Name, $.records[*].StageName, $.records[*].Amount, $.totalSize',
    },
    {
      name: 'get_accounts',
      description: 'Query accounts from Salesforce',
      endpoint: '/services/data/{apiVersion}/query',
      method: 'GET',
      category: 'accounts',
      parameters: [
        {
          name: 'apiVersion',
          type: 'string',
          label: 'API Version',
          description: 'Salesforce API version',
          required: false,
          defaultValue: 'v59.0',
          inPath: true,
        },
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Maximum number of accounts',
          required: false,
          defaultValue: 50,
          inQuery: true,
        },
        {
          name: 'fields',
          type: 'string',
          label: 'Fields',
          description: 'Comma-separated fields',
          required: false,
          defaultValue: 'Id,Name,Industry,Phone,Website,BillingCity,CreatedDate',
          inQuery: true,
        },
        {
          name: 'where',
          type: 'string',
          label: 'WHERE Clause',
          description: 'SOQL WHERE condition',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.records[*].Id, $.records[*].Name, $.records[*].Industry, $.totalSize',
    },
    {
      name: 'execute_soql',
      description: 'Execute a custom SOQL query',
      endpoint: '/services/data/{apiVersion}/query',
      method: 'GET',
      category: 'query',
      parameters: [
        {
          name: 'apiVersion',
          type: 'string',
          label: 'API Version',
          description: 'Salesforce API version',
          required: false,
          defaultValue: 'v59.0',
          inPath: true,
        },
        {
          name: 'q',
          type: 'string',
          label: 'SOQL Query',
          description: 'Full SOQL query string',
          required: true,
          inQuery: true,
        },
      ],
      returns: '$.records, $.totalSize, $.done',
    },
    {
      name: 'create_contact',
      description: 'Create a new contact',
      endpoint: '/services/data/{apiVersion}/sobjects/Contact',
      method: 'POST',
      category: 'contacts',
      parameters: [
        {
          name: 'apiVersion',
          type: 'string',
          label: 'API Version',
          description: 'Salesforce API version',
          required: false,
          defaultValue: 'v59.0',
          inPath: true,
        },
        {
          name: 'FirstName',
          type: 'string',
          label: 'First Name',
          description: 'Contact first name',
          required: false,
          inBody: true,
        },
        {
          name: 'LastName',
          type: 'string',
          label: 'Last Name',
          description: 'Contact last name',
          required: true,
          inBody: true,
        },
        {
          name: 'Email',
          type: 'string',
          label: 'Email',
          description: 'Contact email',
          required: false,
          inBody: true,
        },
        {
          name: 'Phone',
          type: 'string',
          label: 'Phone',
          description: 'Contact phone',
          required: false,
          inBody: true,
        },
        {
          name: 'AccountId',
          type: 'string',
          label: 'Account ID',
          description: 'Related account ID',
          required: false,
          inBody: true,
        },
        {
          name: 'Title',
          type: 'string',
          label: 'Title',
          description: 'Job title',
          required: false,
          inBody: true,
        },
        {
          name: 'Department',
          type: 'string',
          label: 'Department',
          description: 'Department name',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.id, $.success, $.errors',
    },
  ],

  triggers: [
    {
      name: 'lead_created',
      description: 'Triggered when a new lead is created',
      eventType: 'LeadChangeEvent',
      payloadSchema: {
        ChangeEventHeader: 'object',
        FirstName: 'string',
        LastName: 'string',
        Email: 'string',
        Company: 'string',
        Status: 'string',
        CreatedDate: 'string',
      },
      examplePayload: {
        ChangeEventHeader: { entityName: 'Lead', changeType: 'CREATE', recordIds: ['00Q...'] },
        FirstName: 'John',
        LastName: 'Doe',
        Email: 'john@example.com',
        Company: 'Acme Inc',
        Status: 'Open - Not Contacted',
        CreatedDate: '2024-01-15T10:30:00Z',
      },
    },
    {
      name: 'opportunity_updated',
      description: 'Triggered when an opportunity is updated',
      eventType: 'OpportunityChangeEvent',
      payloadSchema: {
        ChangeEventHeader: 'object',
        Name: 'string',
        StageName: 'string',
        Amount: 'number',
        Probability: 'number',
        CloseDate: 'string',
      },
    },
    {
      name: 'case_created',
      description: 'Triggered when a new case is created',
      eventType: 'CaseChangeEvent',
      payloadSchema: {
        ChangeEventHeader: 'object',
        Subject: 'string',
        Status: 'string',
        Priority: 'string',
        Origin: 'string',
        CreatedDate: 'string',
      },
    },
    {
      name: 'account_updated',
      description: 'Triggered when an account is updated',
      eventType: 'AccountChangeEvent',
      payloadSchema: {
        ChangeEventHeader: 'object',
        Name: 'string',
        Industry: 'string',
        Phone: 'string',
        Website: 'string',
      },
    },
  ],
};
