/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║                         SHOPIFY CONNECTOR                                 ║
 * ║        Manage products, orders, inventory, and customers                  ║
 * ║  Production-hardened: Leaky Bucket rate limiting, retries, health        ║
 * ║  checks, webhook HMAC verification, sandbox mode                         ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */

import { ExternalConnectorDefinition } from '../key-cortex-external-connector.types';

export const ShopifyConnector: ExternalConnectorDefinition = {
  id: 'shopify',
  name: 'Shopify',
  description: 'Manage products, orders, inventory, and customers in your Shopify store',
  category: 'ecommerce',
  authType: 'api_key',
  logoUrl: 'https://cdn.keyflow.io/connectors/shopify.svg',
  website: 'https://shopify.com',
  docsUrl: 'https://shopify.dev/api/admin-rest',
  baseUrl: 'https://{shop}.myshopify.com/admin/api/2024-01',
  supportsOAuth: true,
  oauthScopes: [
    'read_products',
    'write_products',
    'read_orders',
    'write_orders',
    'read_inventory',
    'write_inventory',
    'read_customers',
    'write_customers',
    'read_fulfillments',
    'read_analytics',
  ],
  defaultHeaders: {
    'Content-Type': 'application/json',
  },

  // ── Legacy rate limit (backward compatibility) ──────────────────────────
  rateLimit: {
    requestsPerWindow: 40,
    windowSeconds: 60,
    burstLimit: 40,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PRODUCTION HARDENING
  // ══════════════════════════════════════════════════════════════════════════

  /** Rate limiting — Shopify Leaky Bucket: 2/sec, burst 40 */
  rateLimitHardened: {
    requestsPerSecond: 2,
    requestsPerMinute: 120,
    requestsPerHour: 7200,
    burstAllowance: 40,
  },

  /** Retry configuration with exponential backoff + jitter */
  retryConfig: {
    maxRetries: 3,
    baseDelayMs: 1000,
    maxDelayMs: 30000,
    retryableStatusCodes: [429, 500, 502, 503, 504],
    retryableErrors: ['ECONNRESET', 'ETIMEDOUT', 'ENOTFOUND', 'ECONNREFUSED'],
  },

  /** Timeout configuration */
  timeoutConfig: {
    connectTimeoutMs: 10000,
    requestTimeoutMs: 30000,
    uploadTimeoutMs: 120000,
  },

  /** Health check endpoint */
  healthCheck: {
    endpoint: '/shop.json',
    method: 'GET',
    expectedStatus: 200,
    expectedResponse: { shop: { id: 'number', name: 'string' } },
  },

  /** Webhook signature verification (HMAC-SHA256 base64) */
  webhookSecurity: {
    signatureHeader: 'x-shopify-hmac-sha256',
    signatureAlgorithm: 'hmac-sha256',
    signatureFormat: 'base64',
  },

  /** Required OAuth scopes for core functionality */
  requiredScopes: [
    'read_products',
    'write_products',
    'read_orders',
    'write_orders',
    'read_inventory',
    'write_inventory',
    'read_customers',
    'write_customers',
    'read_fulfillments',
  ],

  /** Sandbox/test endpoints */
  sandboxEndpoints: {
    baseUrl: 'https://{shop}.myshopify.com/admin/api/2024-01',
    authUrl: 'https://{shop}.myshopify.com/admin/oauth/access_token',
  },

  // ══════════════════════════════════════════════════════════════════════════

  configSchema: [
    {
      name: 'shopDomain',
      type: 'string',
      label: 'Shop Domain',
      description: 'Your Shopify store domain (e.g., mystore.myshopify.com)',
      required: true,
      placeholder: 'mystore.myshopify.com',
      validationPattern: '^[a-zA-Z0-9][-a-zA-Z0-9]*\\.myshopify\\.com$',
    },
    {
      name: 'apiKey',
      type: 'password',
      label: 'Admin API Access Token',
      description: 'Admin API access token from Shopify Partners dashboard',
      required: true,
      placeholder: 'shpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      secret: true,
    },
    {
      name: 'apiVersion',
      type: 'select',
      label: 'API Version',
      description: 'Shopify Admin API version to use',
      required: true,
      defaultValue: '2024-01',
      options: [
        { label: '2024-01', value: '2024-01' },
        { label: '2024-04', value: '2024-04' },
        { label: '2024-07', value: '2024-07' },
        { label: '2024-10', value: '2024-10' },
        { label: '2025-01', value: '2025-01' },
      ],
    },
    {
      name: 'apiSecret',
      type: 'password',
      label: 'API Secret Key',
      description: 'API secret key for webhook verification',
      required: false,
      placeholder: 'shpss_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      secret: true,
    },
  ],

  actions: [
    {
      name: 'get_products',
      description: 'Get a list of products from the store',
      endpoint: '/products.json',
      method: 'GET',
      category: 'products',
      requiredScope: 'read_products',
      parameters: [
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Number of products to return (1-250)',
          required: false,
          defaultValue: 50,
          inQuery: true,
        },
        {
          name: 'page_info',
          type: 'string',
          label: 'Page Info',
          description: 'Pagination cursor from previous response',
          required: false,
          inQuery: true,
        },
        {
          name: 'ids',
          type: 'string',
          label: 'Product IDs',
          description: 'Comma-separated list of product IDs to filter',
          required: false,
          inQuery: true,
        },
        {
          name: 'collection_id',
          type: 'string',
          label: 'Collection ID',
          description: 'Filter by collection ID',
          required: false,
          inQuery: true,
        },
        {
          name: 'product_type',
          type: 'string',
          label: 'Product Type',
          description: 'Filter by product type',
          required: false,
          inQuery: true,
        },
        {
          name: 'vendor',
          type: 'string',
          label: 'Vendor',
          description: 'Filter by vendor name',
          required: false,
          inQuery: true,
        },
        {
          name: 'status',
          type: 'string',
          label: 'Status',
          description: 'Filter by status: active, archived, draft',
          required: false,
          inQuery: true,
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Archived', value: 'archived' },
            { label: 'Draft', value: 'draft' },
          ],
        },
      ],
      returns: '$.products[*].id, $.products[*].title, $.products[*].variants',
    },
    {
      name: 'create_product',
      description: 'Create a new product in the store',
      endpoint: '/products.json',
      method: 'POST',
      category: 'products',
      requiredScope: 'write_products',
      parameters: [
        {
          name: 'title',
          type: 'string',
          label: 'Product Title',
          description: 'Title of the product',
          required: true,
          inBody: true,
        },
        {
          name: 'body_html',
          type: 'textarea',
          label: 'Description',
          description: 'HTML description of the product',
          required: false,
          inBody: true,
        },
        {
          name: 'vendor',
          type: 'string',
          label: 'Vendor',
          description: 'Vendor/manufacturer name',
          required: false,
          inBody: true,
        },
        {
          name: 'product_type',
          type: 'string',
          label: 'Product Type',
          description: 'Category/type of product',
          required: false,
          inBody: true,
        },
        {
          name: 'tags',
          type: 'string',
          label: 'Tags',
          description: 'Comma-separated list of tags',
          required: false,
          inBody: true,
        },
        {
          name: 'variants',
          type: 'json',
          label: 'Variants',
          description: 'Product variants array with price, sku, inventory_quantity',
          required: false,
          inBody: true,
        },
        {
          name: 'images',
          type: 'json',
          label: 'Images',
          description: 'Array of image objects with src',
          required: false,
          inBody: true,
        },
        {
          name: 'status',
          type: 'string',
          label: 'Status',
          description: 'Product status',
          required: false,
          defaultValue: 'active',
          inBody: true,
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Draft', value: 'draft' },
            { label: 'Archived', value: 'archived' },
          ],
        },
      ],
      returns: '$.product.id, $.product.title, $.product.variants[*].id',
      examplePayload: {
        product: {
          title: 'New Product',
          body_html: '<p>Great product description</p>',
          vendor: 'My Brand',
          product_type: 'Widget',
          tags: 'new, featured',
          variants: [{ price: '19.99', sku: 'PROD-001', inventory_quantity: 100 }],
        },
      },
    },
    {
      name: 'update_product',
      description: 'Update an existing product',
      endpoint: '/products/{product_id}.json',
      method: 'PUT',
      category: 'products',
      requiredScope: 'write_products',
      parameters: [
        {
          name: 'product_id',
          type: 'number',
          label: 'Product ID',
          description: 'ID of the product to update',
          required: true,
          inPath: true,
        },
        {
          name: 'title',
          type: 'string',
          label: 'Product Title',
          description: 'Updated title',
          required: false,
          inBody: true,
        },
        {
          name: 'body_html',
          type: 'textarea',
          label: 'Description',
          description: 'Updated HTML description',
          required: false,
          inBody: true,
        },
        {
          name: 'tags',
          type: 'string',
          label: 'Tags',
          description: 'Updated comma-separated tags',
          required: false,
          inBody: true,
        },
        {
          name: 'status',
          type: 'string',
          label: 'Status',
          description: 'Updated status',
          required: false,
          inBody: true,
        },
        {
          name: 'variants',
          type: 'json',
          label: 'Variants',
          description: 'Updated variants array',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.product.id, $.product.title, $.product.updated_at',
    },
    {
      name: 'get_orders',
      description: 'Get a list of orders from the store',
      endpoint: '/orders.json',
      method: 'GET',
      category: 'orders',
      requiredScope: 'read_orders',
      parameters: [
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Number of orders to return (1-250)',
          required: false,
          defaultValue: 50,
          inQuery: true,
        },
        {
          name: 'status',
          type: 'string',
          label: 'Status',
          description: 'Filter by order status',
          required: false,
          inQuery: true,
          options: [
            { label: 'Open', value: 'open' },
            { label: 'Closed', value: 'closed' },
            { label: 'Cancelled', value: 'cancelled' },
            { label: 'Any', value: 'any' },
          ],
        },
        {
          name: 'financial_status',
          type: 'string',
          label: 'Financial Status',
          description: 'Filter by financial status',
          required: false,
          inQuery: true,
        },
        {
          name: 'fulfillment_status',
          type: 'string',
          label: 'Fulfillment Status',
          description: 'Filter by fulfillment status',
          required: false,
          inQuery: true,
        },
        {
          name: 'created_at_min',
          type: 'string',
          label: 'Created After',
          description: 'ISO 8601 datetime for minimum creation time',
          required: false,
          inQuery: true,
        },
        {
          name: 'created_at_max',
          type: 'string',
          label: 'Created Before',
          description: 'ISO 8601 datetime for maximum creation time',
          required: false,
          inQuery: true,
        },
        {
          name: 'fields',
          type: 'string',
          label: 'Fields',
          description: 'Comma-separated list of fields to return',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.orders[*].id, $.orders[*].name, $.orders[*].total_price, $.orders[*].financial_status',
    },
    {
      name: 'get_order',
      description: 'Get a single order by ID',
      endpoint: '/orders/{order_id}.json',
      method: 'GET',
      category: 'orders',
      requiredScope: 'read_orders',
      parameters: [
        {
          name: 'order_id',
          type: 'number',
          label: 'Order ID',
          description: 'ID of the order to retrieve',
          required: true,
          inPath: true,
        },
        {
          name: 'fields',
          type: 'string',
          label: 'Fields',
          description: 'Comma-separated fields to return',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.order.id, $.order.name, $.order.line_items, $.order.shipping_address',
    },
    {
      name: 'update_inventory',
      description: 'Update inventory levels for a product variant',
      endpoint: '/inventory_levels/set.json',
      method: 'POST',
      category: 'inventory',
      requiredScope: 'write_inventory',
      parameters: [
        {
          name: 'inventory_item_id',
          type: 'number',
          label: 'Inventory Item ID',
          description: 'ID of the inventory item',
          required: true,
          inBody: true,
        },
        {
          name: 'location_id',
          type: 'number',
          label: 'Location ID',
          description: 'ID of the location',
          required: true,
          inBody: true,
        },
        {
          name: 'available',
          type: 'number',
          label: 'Available Quantity',
          description: 'New available quantity',
          required: true,
          inBody: true,
        },
      ],
      returns: '$.inventory_level.inventory_item_id, $.inventory_level.available, $.inventory_level.location_id',
    },
    {
      name: 'get_customers',
      description: 'Get a list of customers',
      endpoint: '/customers.json',
      method: 'GET',
      category: 'customers',
      requiredScope: 'read_customers',
      parameters: [
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Number of customers to return (1-250)',
          required: false,
          defaultValue: 50,
          inQuery: true,
        },
        {
          name: 'ids',
          type: 'string',
          label: 'Customer IDs',
          description: 'Comma-separated customer IDs',
          required: false,
          inQuery: true,
        },
        {
          name: 'email',
          type: 'string',
          label: 'Email',
          description: 'Filter by email address',
          required: false,
          inQuery: true,
        },
        {
          name: 'created_at_min',
          type: 'string',
          label: 'Created After',
          description: 'Minimum creation date (ISO 8601)',
          required: false,
          inQuery: true,
        },
        {
          name: 'fields',
          type: 'string',
          label: 'Fields',
          description: 'Comma-separated fields to return',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.customers[*].id, $.customers[*].email, $.customers[*].first_name, $.customers[*].last_name',
    },
    {
      name: 'create_customer',
      description: 'Create a new customer',
      endpoint: '/customers.json',
      method: 'POST',
      category: 'customers',
      requiredScope: 'write_customers',
      parameters: [
        {
          name: 'first_name',
          type: 'string',
          label: 'First Name',
          description: 'Customer first name',
          required: false,
          inBody: true,
        },
        {
          name: 'last_name',
          type: 'string',
          label: 'Last Name',
          description: 'Customer last name',
          required: false,
          inBody: true,
        },
        {
          name: 'email',
          type: 'string',
          label: 'Email',
          description: 'Customer email address',
          required: true,
          inBody: true,
        },
        {
          name: 'phone',
          type: 'string',
          label: 'Phone',
          description: 'Customer phone number',
          required: false,
          inBody: true,
        },
        {
          name: 'tags',
          type: 'string',
          label: 'Tags',
          description: 'Comma-separated tags',
          required: false,
          inBody: true,
        },
        {
          name: 'addresses',
          type: 'json',
          label: 'Addresses',
          description: 'Array of address objects',
          required: false,
          inBody: true,
        },
        {
          name: 'note',
          type: 'string',
          label: 'Note',
          description: 'Additional note about the customer',
          required: false,
          inBody: true,
        },
        {
          name: 'verified_email',
          type: 'boolean',
          label: 'Verified Email',
          description: 'Whether the email is verified',
          required: false,
          defaultValue: true,
          inBody: true,
        },
      ],
      returns: '$.customer.id, $.customer.email, $.customer.created_at',
    },
    {
      name: 'get_inventory_levels',
      description: 'Get inventory levels for an item',
      endpoint: '/inventory_levels.json',
      method: 'GET',
      category: 'inventory',
      requiredScope: 'read_inventory',
      parameters: [
        {
          name: 'inventory_item_ids',
          type: 'string',
          label: 'Inventory Item IDs',
          description: 'Comma-separated inventory item IDs',
          required: true,
          inQuery: true,
        },
        {
          name: 'location_ids',
          type: 'string',
          label: 'Location IDs',
          description: 'Comma-separated location IDs',
          required: false,
          inQuery: true,
        },
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Maximum results to return',
          required: false,
          defaultValue: 50,
          inQuery: true,
        },
      ],
      returns: '$.inventory_levels[*].inventory_item_id, $.inventory_levels[*].available, $.inventory_levels[*].location_id',
    },
    {
      name: 'create_fulfillment',
      description: 'Create a fulfillment for an order',
      endpoint: '/orders/{order_id}/fulfillments.json',
      method: 'POST',
      category: 'orders',
      requiredScope: 'write_orders',
      parameters: [
        {
          name: 'order_id',
          type: 'number',
          label: 'Order ID',
          description: 'ID of the order to fulfill',
          required: true,
          inPath: true,
        },
        {
          name: 'location_id',
          type: 'number',
          label: 'Location ID',
          description: 'ID of the fulfillment location',
          required: true,
          inBody: true,
        },
        {
          name: 'tracking_number',
          type: 'string',
          label: 'Tracking Number',
          description: 'Shipping tracking number',
          required: false,
          inBody: true,
        },
        {
          name: 'tracking_company',
          type: 'string',
          label: 'Tracking Company',
          description: 'Shipping carrier name',
          required: false,
          inBody: true,
        },
        {
          name: 'line_items',
          type: 'json',
          label: 'Line Items',
          description: 'Array of line items to fulfill with id and quantity',
          required: false,
          inBody: true,
        },
        {
          name: 'notify_customer',
          type: 'boolean',
          label: 'Notify Customer',
          description: 'Send shipping confirmation to customer',
          required: false,
          defaultValue: true,
          inBody: true,
        },
      ],
      returns: '$.fulfillment.id, $.fulfillment.tracking_number, $.fulfillment.status',
    },
  ],

  triggers: [
    {
      name: 'order_created',
      description: 'Triggered when a new order is placed',
      eventType: 'orders/create',
      payloadSchema: {
        id: 'number',
        name: 'string',
        email: 'string',
        total_price: 'string',
        financial_status: 'string',
        fulfillment_status: 'string?',
        line_items: 'array',
        created_at: 'string',
      },
      examplePayload: {
        id: 123456789,
        name: '#1001',
        email: 'customer@example.com',
        total_price: '99.99',
        financial_status: 'paid',
        line_items: [{ product_id: 123, quantity: 2, price: '49.99' }],
        created_at: '2024-01-15T10:30:00Z',
      },
    },
    {
      name: 'order_updated',
      description: 'Triggered when an order is updated',
      eventType: 'orders/updated',
      payloadSchema: {
        id: 'number',
        name: 'string',
        financial_status: 'string',
        fulfillment_status: 'string?',
        updated_at: 'string',
      },
    },
    {
      name: 'product_created',
      description: 'Triggered when a product is created',
      eventType: 'products/create',
      payloadSchema: {
        id: 'number',
        title: 'string',
        vendor: 'string',
        product_type: 'string',
        variants: 'array',
        created_at: 'string',
      },
    },
    {
      name: 'product_updated',
      description: 'Triggered when a product is updated',
      eventType: 'products/update',
      payloadSchema: {
        id: 'number',
        title: 'string',
        variants: 'array',
        updated_at: 'string',
      },
    },
    {
      name: 'customer_created',
      description: 'Triggered when a customer is created',
      eventType: 'customers/create',
      payloadSchema: {
        id: 'number',
        email: 'string',
        first_name: 'string',
        last_name: 'string',
        created_at: 'string',
      },
    },
    {
      name: 'checkout_created',
      description: 'Triggered when a checkout is created',
      eventType: 'checkouts/create',
      payloadSchema: {
        id: 'number',
        token: 'string',
        email: 'string',
        line_items: 'array',
        total_price: 'string',
        created_at: 'string',
      },
      isPremium: true,
    },
    {
      name: 'app_uninstalled',
      description: 'Triggered when the app is uninstalled',
      eventType: 'app/uninstalled',
      payloadSchema: {
        shop_id: 'number',
        shop_domain: 'string',
        timestamp: 'string',
      },
    },
  ],
};
