/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║                         SLACK CONNECTOR                                   ║
 * ║          Send messages, manage channels, upload files                     ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */

import { ExternalConnectorDefinition } from '../key-cortex-external-connector.types';

export const SlackConnector: ExternalConnectorDefinition = {
  id: 'slack',
  name: 'Slack',
  description: 'Send messages, manage channels, and automate Slack workspaces',
  category: 'communication',
  authType: 'oauth2',
  logoUrl: 'https://cdn.keyflow.io/connectors/slack.svg',
  website: 'https://slack.com',
  docsUrl: 'https://api.slack.com/docs',
  baseUrl: 'https://slack.com/api',
  supportsOAuth: true,
  oauthScopes: [
    'chat:write',
    'channels:read',
    'channels:manage',
    'users:read',
    'files:write',
    'groups:read',
    'im:read',
    'mpim:read',
    'team:read',
  ],
  defaultHeaders: {
    'Content-Type': 'application/json; charset=utf-8',
  },
  rateLimit: {
    requestsPerWindow: 100,
    windowSeconds: 60,
    burstLimit: 10,
  },

  configSchema: [
    {
      name: 'workspace',
      type: 'string',
      label: 'Workspace Name',
      description: 'Your Slack workspace name (e.g., mycompany)',
      required: true,
      placeholder: 'mycompany',
    },
    {
      name: 'botToken',
      type: 'password',
      label: 'Bot User OAuth Token',
      description: 'Bot User OAuth Token from Slack app settings',
      required: true,
      placeholder: 'xoxb-...',
      secret: true,
    },
    {
      name: 'userToken',
      type: 'password',
      label: 'User OAuth Token',
      description: 'User OAuth Token (optional, for user-context actions)',
      required: false,
      placeholder: 'xoxp-...',
      secret: true,
    },
    {
      name: 'signingSecret',
      type: 'password',
      label: 'Signing Secret',
      description: 'Slack app signing secret for webhook verification',
      required: false,
      placeholder: '...',
      secret: true,
    },
    {
      name: 'defaultChannel',
      type: 'string',
      label: 'Default Channel',
      description: 'Default channel to post messages (without # prefix)',
      required: false,
      placeholder: 'general',
    },
  ],

  actions: [
    {
      name: 'send_message',
      description: 'Send a message to a Slack channel or user',
      endpoint: '/chat.postMessage',
      method: 'POST',
      category: 'messaging',
      requiredScope: 'chat:write',
      parameters: [
        {
          name: 'channel',
          type: 'string',
          label: 'Channel',
          description: 'Channel ID or name (e.g., #general) or user ID',
          required: true,
          inBody: true,
        },
        {
          name: 'text',
          type: 'string',
          label: 'Message Text',
          description: 'The message text to send',
          required: true,
          inBody: true,
        },
        {
          name: 'blocks',
          type: 'json',
          label: 'Block Kit Blocks',
          description: 'Rich Block Kit JSON blocks for advanced formatting',
          required: false,
          inBody: true,
        },
        {
          name: 'thread_ts',
          type: 'string',
          label: 'Thread Timestamp',
          description: 'Timestamp of parent message to reply in thread',
          required: false,
          inBody: true,
        },
        {
          name: 'unfurl_links',
          type: 'boolean',
          label: 'Unfurl Links',
          description: 'Enable/disable link unfurling',
          required: false,
          defaultValue: true,
          inBody: true,
        },
      ],
      returns: '$.ok, $.channel, $.ts, $.message',
      examplePayload: {
        channel: '#general',
        text: 'Hello from KeyFlowOS!',
        unfurl_links: true,
      },
    },
    {
      name: 'create_channel',
      description: 'Create a new public or private channel',
      endpoint: '/conversations.create',
      method: 'POST',
      category: 'channel_management',
      requiredScope: 'channels:manage',
      parameters: [
        {
          name: 'name',
          type: 'string',
          label: 'Channel Name',
          description: 'Name of the channel (lowercase, no spaces)',
          required: true,
          inBody: true,
        },
        {
          name: 'is_private',
          type: 'boolean',
          label: 'Private',
          description: 'Create as a private channel',
          required: false,
          defaultValue: false,
          inBody: true,
        },
        {
          name: 'team_id',
          type: 'string',
          label: 'Team ID',
          description: 'Team/workspace ID (for Enterprise Grid)',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.ok, $.channel.id, $.channel.name, $.channel.created',
    },
    {
      name: 'invite_user',
      description: 'Invite a user to a channel',
      endpoint: '/conversations.invite',
      method: 'POST',
      category: 'channel_management',
      requiredScope: 'channels:manage',
      parameters: [
        {
          name: 'channel',
          type: 'string',
          label: 'Channel ID',
          description: 'ID of the channel to invite to',
          required: true,
          inBody: true,
        },
        {
          name: 'users',
          type: 'string',
          label: 'User IDs',
          description: 'Comma-separated list of user IDs to invite',
          required: true,
          inBody: true,
        },
      ],
      returns: '$.ok, $.channel',
    },
    {
      name: 'upload_file',
      description: 'Upload a file to Slack',
      endpoint: '/files.upload',
      method: 'POST',
      category: 'files',
      requiredScope: 'files:write',
      parameters: [
        {
          name: 'content',
          type: 'string',
          label: 'File Content',
          description: 'File contents as a string or base64',
          required: false,
          inBody: true,
        },
        {
          name: 'file',
          type: 'file',
          label: 'File',
          description: 'File to upload (multipart)',
          required: false,
          inBody: true,
        },
        {
          name: 'filename',
          type: 'string',
          label: 'Filename',
          description: 'Name of the file',
          required: true,
          inBody: true,
        },
        {
          name: 'channels',
          type: 'string',
          label: 'Channels',
          description: 'Comma-separated list of channel IDs to share to',
          required: false,
          inBody: true,
        },
        {
          name: 'initial_comment',
          type: 'string',
          label: 'Initial Comment',
          description: 'Message text to include with the file',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.ok, $.file.id, $.file.name, $.file.permalink',
    },
    {
      name: 'get_channels',
      description: 'List all channels in the workspace',
      endpoint: '/conversations.list',
      method: 'GET',
      category: 'channel_management',
      requiredScope: 'channels:read',
      parameters: [
        {
          name: 'types',
          type: 'string',
          label: 'Channel Types',
          description: 'Comma-separated: public_channel, private_channel, mpim, im',
          required: false,
          defaultValue: 'public_channel',
          inQuery: true,
        },
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Maximum number of channels to return (1-200)',
          required: false,
          defaultValue: 100,
          inQuery: true,
        },
        {
          name: 'cursor',
          type: 'string',
          label: 'Pagination Cursor',
          description: 'Cursor for pagination',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.ok, $.channels[*].id, $.channels[*].name, $.channels[*].num_members',
    },
    {
      name: 'get_channel_info',
      description: 'Get detailed information about a channel',
      endpoint: '/conversations.info',
      method: 'GET',
      category: 'channel_management',
      requiredScope: 'channels:read',
      parameters: [
        {
          name: 'channel',
          type: 'string',
          label: 'Channel ID',
          description: 'ID of the channel',
          required: true,
          inQuery: true,
        },
      ],
      returns: '$.ok, $.channel.id, $.channel.name, $.channel.members',
    },
    {
      name: 'archive_channel',
      description: 'Archive a channel',
      endpoint: '/conversations.archive',
      method: 'POST',
      category: 'channel_management',
      requiredScope: 'channels:manage',
      parameters: [
        {
          name: 'channel',
          type: 'string',
          label: 'Channel ID',
          description: 'ID of the channel to archive',
          required: true,
          inBody: true,
        },
      ],
      returns: '$.ok',
    },
    {
      name: 'get_users',
      description: 'List all users in the workspace',
      endpoint: '/users.list',
      method: 'GET',
      category: 'users',
      requiredScope: 'users:read',
      parameters: [
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Maximum number of users to return',
          required: false,
          defaultValue: 100,
          inQuery: true,
        },
        {
          name: 'cursor',
          type: 'string',
          label: 'Pagination Cursor',
          description: 'Cursor for pagination',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.ok, $.members[*].id, $.members[*].name, $.members[*].profile.email',
    },
    {
      name: 'update_message',
      description: 'Update an existing message',
      endpoint: '/chat.update',
      method: 'POST',
      category: 'messaging',
      requiredScope: 'chat:write',
      parameters: [
        {
          name: 'channel',
          type: 'string',
          label: 'Channel ID',
          description: 'Channel containing the message',
          required: true,
          inBody: true,
        },
        {
          name: 'ts',
          type: 'string',
          label: 'Message Timestamp',
          description: 'Timestamp of the message to update',
          required: true,
          inBody: true,
        },
        {
          name: 'text',
          type: 'string',
          label: 'New Message Text',
          description: 'Updated message text',
          required: false,
          inBody: true,
        },
        {
          name: 'blocks',
          type: 'json',
          label: 'Block Kit Blocks',
          description: 'Updated Block Kit blocks',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.ok, $.channel, $.ts, $.text',
    },
  ],

  triggers: [
    {
      name: 'message_received',
      description: 'Triggered when a message is posted to a channel',
      eventType: 'message',
      payloadSchema: {
        type: 'string',
        user: 'string',
        channel: 'string',
        text: 'string',
        ts: 'string',
        thread_ts: 'string?',
        team: 'string',
      },
      examplePayload: {
        type: 'message',
        user: 'U12345678',
        channel: 'C12345678',
        text: 'Hello world',
        ts: '1234567890.123456',
        team: 'T12345678',
      },
    },
    {
      name: 'app_mention',
      description: 'Triggered when the app is mentioned in a message',
      eventType: 'app_mention',
      payloadSchema: {
        type: 'string',
        user: 'string',
        channel: 'string',
        text: 'string',
        ts: 'string',
        team: 'string',
      },
      examplePayload: {
        type: 'app_mention',
        user: 'U12345678',
        channel: 'C12345678',
        text: '<@U00ABCDEF> help',
        ts: '1234567890.123456',
        team: 'T12345678',
      },
    },
    {
      name: 'member_joined_channel',
      description: 'Triggered when a user joins a channel',
      eventType: 'member_joined_channel',
      payloadSchema: {
        user: 'string',
        channel: 'string',
        channel_type: 'string',
        team: 'string',
        inviter: 'string?',
      },
    },
    {
      name: 'reaction_added',
      description: 'Triggered when a reaction is added to a message',
      eventType: 'reaction_added',
      payloadSchema: {
        user: 'string',
        reaction: 'string',
        item_user: 'string',
        item: 'object',
        event_ts: 'string',
      },
    },
    {
      name: 'channel_created',
      description: 'Triggered when a new channel is created',
      eventType: 'channel_created',
      payloadSchema: {
        channel: 'object',
        event_ts: 'string',
      },
      isPremium: true,
    },
  ],
};
