/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║                         STRIPE CONNECTOR                                  ║
 * ║      Process payments, manage subscriptions, handle refunds              ║
 * ║  Production-hardened: 100/sec read+write rate limits, retries,         ║
 * ║  webhook signature verification, health checks, sandbox mode             ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */

import { ExternalConnectorDefinition } from '../key-cortex-external-connector.types';

export const StripeExternalConnector: ExternalConnectorDefinition = {
  id: 'stripe',
  name: 'Stripe',
  description: 'Process payments, manage subscriptions, create refunds, and track customers',
  category: 'payment',
  authType: 'api_key',
  logoUrl: 'https://cdn.keyflow.io/connectors/stripe.svg',
  website: 'https://stripe.com',
  docsUrl: 'https://stripe.com/docs/api',
  baseUrl: 'https://api.stripe.com',
  supportsOAuth: true,
  oauthScopes: ['read_write'],
  defaultHeaders: {
    'Content-Type': 'application/x-www-form-urlencoded',
  },

  // ── Legacy rate limit (backward compatibility) ──────────────────────────
  rateLimit: {
    requestsPerWindow: 100,
    windowSeconds: 60,
    burstLimit: 100,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PRODUCTION HARDENING
  // ══════════════════════════════════════════════════════════════════════════

  /** Rate limiting — Stripe: 100/sec read, 100/sec write */
  rateLimitHardened: {
    requestsPerSecond: 100,
    requestsPerMinute: 6000,
    requestsPerHour: 360000,
    burstAllowance: 100,
  },

  /** Retry configuration with exponential backoff + jitter */
  retryConfig: {
    maxRetries: 3,
    baseDelayMs: 500,
    maxDelayMs: 30000,
    retryableStatusCodes: [409, 429, 500, 502, 503, 504],
    retryableErrors: ['ECONNRESET', 'ETIMEDOUT', 'ENOTFOUND', 'ECONNREFUSED'],
  },

  /** Timeout configuration */
  timeoutConfig: {
    connectTimeoutMs: 5000,
    requestTimeoutMs: 30000,
    uploadTimeoutMs: 120000,
  },

  /** Health check endpoint — Stripe account endpoint */
  healthCheck: {
    endpoint: '/v1/account',
    method: 'GET',
    expectedStatus: 200,
  },

  /** Webhook security — Stripe uses v1=timestamp,signature format */
  webhookSecurity: {
    signatureHeader: 'stripe-signature',
    signatureAlgorithm: 'hmac-sha256',
    signatureFormat: 'hex',
    timestampHeader: 't',
    timestampToleranceSeconds: 300,
  },

  /** Required OAuth scopes */
  requiredScopes: ['read_write'],

  /** Sandbox/test endpoints — Stripe has separate test environment */
  sandboxEndpoints: {
    baseUrl: 'https://api.stripe.com',
    authUrl: 'https://connect.stripe.com/oauth/token',
  },

  // ══════════════════════════════════════════════════════════════════════════

  configSchema: [
    {
      name: 'apiKey',
      type: 'password',
      label: 'Secret API Key',
      description: 'Stripe secret API key (sk_live_... or sk_test_...)',
      required: true,
      placeholder: 'sk_...your_secret_key_here...',
      secret: true,
    },
    {
      name: 'webhookSecret',
      type: 'password',
      label: 'Webhook Endpoint Secret',
      description: 'Webhook endpoint secret for signature verification (whsec_...)',
      required: false,
      placeholder: 'whsec_...your_webhook_secret_here...',
      secret: true,
    },
    {
      name: 'apiVersion',
      type: 'select',
      label: 'API Version',
      description: 'Stripe API version to use',
      required: true,
      defaultValue: '2024-04-10',
      options: [
        { label: '2024-04-10', value: '2024-04-10' },
        { label: '2024-06-20', value: '2024-06-20' },
        { label: '2024-09-30', value: '2024-09-30' },
        { label: '2024-12-18', value: '2024-12-18' },
      ],
    },
    {
      name: 'environment',
      type: 'select',
      label: 'Environment',
      description: 'Stripe environment mode',
      required: true,
      defaultValue: 'live',
      options: [
        { label: 'Live Mode', value: 'live' },
        { label: 'Test Mode', value: 'test' },
      ],
    },
  ],

  actions: [
    {
      name: 'get_charges',
      description: 'List all charges with optional filters',
      endpoint: '/v1/charges',
      method: 'GET',
      category: 'charges',
      parameters: [
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Maximum number of charges (1-100)',
          required: false,
          defaultValue: 10,
          inQuery: true,
        },
        {
          name: 'starting_after',
          type: 'string',
          label: 'Starting After',
          description: 'Pagination cursor',
          required: false,
          inQuery: true,
        },
        {
          name: 'customer',
          type: 'string',
          label: 'Customer ID',
          description: 'Filter by customer ID',
          required: false,
          inQuery: true,
        },
        {
          name: 'created[gte]',
          type: 'number',
          label: 'Created After (Unix Timestamp)',
          description: 'Filter charges created on or after this time',
          required: false,
          inQuery: true,
        },
        {
          name: 'created[lte]',
          type: 'number',
          label: 'Created Before (Unix Timestamp)',
          description: 'Filter charges created on or before this time',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.data[*].id, $.data[*].amount, $.data[*].currency, $.data[*].status, $.has_more',
    },
    {
      name: 'get_charge',
      description: 'Retrieve a single charge by ID',
      endpoint: '/v1/charges/{charge_id}',
      method: 'GET',
      category: 'charges',
      parameters: [
        {
          name: 'charge_id',
          type: 'string',
          label: 'Charge ID',
          description: 'ID of the charge to retrieve',
          required: true,
          inPath: true,
        },
      ],
      returns: '$.id, $.amount, $.currency, $.status, $.receipt_url, $.payment_method_details',
    },
    {
      name: 'create_refund',
      description: 'Create a refund for a charge',
      endpoint: '/v1/refunds',
      method: 'POST',
      category: 'refunds',
      parameters: [
        {
          name: 'charge',
          type: 'string',
          label: 'Charge ID',
          description: 'ID of the charge to refund',
          required: true,
          inBody: true,
        },
        {
          name: 'amount',
          type: 'number',
          label: 'Amount',
          description: 'Amount to refund in cents (omit for full refund)',
          required: false,
          inBody: true,
        },
        {
          name: 'reason',
          type: 'string',
          label: 'Reason',
          description: 'Reason for the refund',
          required: false,
          inBody: true,
          options: [
            { label: 'Duplicate', value: 'duplicate' },
            { label: 'Fraudulent', value: 'fraudulent' },
            { label: 'Requested by Customer', value: 'requested_by_customer' },
          ],
        },
        {
          name: 'metadata',
          type: 'json',
          label: 'Metadata',
          description: 'Set of key-value pairs for additional context',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.id, $.amount, $.status, $.charge, $.reason',
      examplePayload: {
        charge: 'ch_00000000000000',
        amount: 5000,
        reason: 'requested_by_customer',
      },
    },
    {
      name: 'get_subscriptions',
      description: 'List all subscriptions',
      endpoint: '/v1/subscriptions',
      method: 'GET',
      category: 'subscriptions',
      parameters: [
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Maximum number of subscriptions (1-100)',
          required: false,
          defaultValue: 10,
          inQuery: true,
        },
        {
          name: 'starting_after',
          type: 'string',
          label: 'Starting After',
          description: 'Pagination cursor',
          required: false,
          inQuery: true,
        },
        {
          name: 'customer',
          type: 'string',
          label: 'Customer ID',
          description: 'Filter by customer ID',
          required: false,
          inQuery: true,
        },
        {
          name: 'status',
          type: 'string',
          label: 'Status',
          description: 'Filter by subscription status',
          required: false,
          inQuery: true,
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Canceled', value: 'canceled' },
            { label: 'Incomplete', value: 'incomplete' },
            { label: 'Past Due', value: 'past_due' },
            { label: 'Unpaid', value: 'unpaid' },
            { label: 'Trialing', value: 'trialing' },
            { label: 'All', value: 'all' },
          ],
        },
        {
          name: 'price',
          type: 'string',
          label: 'Price ID',
          description: 'Filter by price ID',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.data[*].id, $.data[*].status, $.data[*].current_period_end, $.has_more',
    },
    {
      name: 'get_subscription',
      description: 'Retrieve a single subscription by ID',
      endpoint: '/v1/subscriptions/{subscription_id}',
      method: 'GET',
      category: 'subscriptions',
      parameters: [
        {
          name: 'subscription_id',
          type: 'string',
          label: 'Subscription ID',
          description: 'ID of the subscription to retrieve',
          required: true,
          inPath: true,
        },
      ],
      returns: '$.id, $.status, $.items, $.current_period_start, $.current_period_end',
    },
    {
      name: 'cancel_subscription',
      description: 'Cancel a subscription',
      endpoint: '/v1/subscriptions/{subscription_id}',
      method: 'DELETE',
      category: 'subscriptions',
      parameters: [
        {
          name: 'subscription_id',
          type: 'string',
          label: 'Subscription ID',
          description: 'ID of the subscription to cancel',
          required: true,
          inPath: true,
        },
        {
          name: 'invoice_now',
          type: 'boolean',
          label: 'Invoice Now',
          description: 'Generate a final invoice immediately',
          required: false,
          defaultValue: false,
          inBody: true,
        },
        {
          name: 'prorate',
          type: 'boolean',
          label: 'Prorate',
          description: 'Whether to create a prorated invoice',
          required: false,
          defaultValue: true,
          inBody: true,
        },
      ],
      returns: '$.id, $.status, $.canceled_at',
    },
    {
      name: 'get_customers',
      description: 'List all customers',
      endpoint: '/v1/customers',
      method: 'GET',
      category: 'customers',
      parameters: [
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Maximum number of customers (1-100)',
          required: false,
          defaultValue: 10,
          inQuery: true,
        },
        {
          name: 'starting_after',
          type: 'string',
          label: 'Starting After',
          description: 'Pagination cursor',
          required: false,
          inQuery: true,
        },
        {
          name: 'email',
          type: 'string',
          label: 'Email',
          description: 'Filter by email address',
          required: false,
          inQuery: true,
        },
        {
          name: 'created[gte]',
          type: 'number',
          label: 'Created After',
          description: 'Unix timestamp for minimum creation time',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.data[*].id, $.data[*].email, $.data[*].name, $.data[*].created, $.has_more',
    },
    {
      name: 'create_customer',
      description: 'Create a new customer',
      endpoint: '/v1/customers',
      method: 'POST',
      category: 'customers',
      parameters: [
        {
          name: 'email',
          type: 'string',
          label: 'Email',
          description: 'Customer email address',
          required: false,
          inBody: true,
        },
        {
          name: 'name',
          type: 'string',
          label: 'Name',
          description: 'Customer full name',
          required: false,
          inBody: true,
        },
        {
          name: 'phone',
          type: 'string',
          label: 'Phone',
          description: 'Customer phone number',
          required: false,
          inBody: true,
        },
        {
          name: 'description',
          type: 'string',
          label: 'Description',
          description: 'Arbitrary description or notes',
          required: false,
          inBody: true,
        },
        {
          name: 'metadata',
          type: 'json',
          label: 'Metadata',
          description: 'Key-value pairs for custom data',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.id, $.email, $.name, $.created',
    },
    {
      name: 'create_payment_intent',
      description: 'Create a payment intent to accept a payment',
      endpoint: '/v1/payment_intents',
      method: 'POST',
      category: 'payments',
      parameters: [
        {
          name: 'amount',
          type: 'number',
          label: 'Amount',
          description: 'Amount in cents (e.g., 1000 for $10.00)',
          required: true,
          inBody: true,
        },
        {
          name: 'currency',
          type: 'string',
          label: 'Currency',
          description: 'Three-letter ISO currency code',
          required: true,
          defaultValue: 'usd',
          inBody: true,
        },
        {
          name: 'customer',
          type: 'string',
          label: 'Customer ID',
          description: 'ID of existing customer (optional)',
          required: false,
          inBody: true,
        },
        {
          name: 'description',
          type: 'string',
          label: 'Description',
          description: 'Payment description',
          required: false,
          inBody: true,
        },
        {
          name: 'metadata',
          type: 'json',
          label: 'Metadata',
          description: 'Key-value pairs for custom data',
          required: false,
          inBody: true,
        },
        {
          name: 'receipt_email',
          type: 'string',
          label: 'Receipt Email',
          description: 'Email to send receipt to',
          required: false,
          inBody: true,
        },
        {
          name: 'automatic_payment_methods',
          type: 'json',
          label: 'Automatic Payment Methods',
          description: 'Payment method configuration',
          required: false,
          defaultValue: { enabled: true },
          inBody: true,
        },
      ],
      returns: '$.id, $.client_secret, $.status, $.amount, $.currency',
      examplePayload: {
        amount: 1000,
        currency: 'usd',
        description: 'Payment for Order #123',
      },
    },
    {
      name: 'get_products',
      description: 'List all products from Stripe',
      endpoint: '/v1/products',
      method: 'GET',
      category: 'products',
      parameters: [
        {
          name: 'limit',
          type: 'number',
          label: 'Limit',
          description: 'Maximum number of products (1-100)',
          required: false,
          defaultValue: 10,
          inQuery: true,
        },
        {
          name: 'starting_after',
          type: 'string',
          label: 'Starting After',
          description: 'Pagination cursor',
          required: false,
          inQuery: true,
        },
        {
          name: 'active',
          type: 'boolean',
          label: 'Active Only',
          description: 'Only return active products',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.data[*].id, $.data[*].name, $.data[*].active, $.has_more',
    },
    {
      name: 'create_invoice',
      description: 'Create an invoice for a customer',
      endpoint: '/v1/invoices',
      method: 'POST',
      category: 'invoicing',
      parameters: [
        {
          name: 'customer',
          type: 'string',
          label: 'Customer ID',
          description: 'ID of the customer to invoice',
          required: true,
          inBody: true,
        },
        {
          name: 'collection_method',
          type: 'string',
          label: 'Collection Method',
          description: 'How to collect payment',
          required: false,
          defaultValue: 'charge_automatically',
          inBody: true,
          options: [
            { label: 'Charge Automatically', value: 'charge_automatically' },
            { label: 'Send Invoice', value: 'send_invoice' },
          ],
        },
        {
          name: 'description',
          type: 'string',
          label: 'Description',
          description: 'Invoice description',
          required: false,
          inBody: true,
        },
        {
          name: 'metadata',
          type: 'json',
          label: 'Metadata',
          description: 'Key-value pairs for custom data',
          required: false,
          inBody: true,
        },
        {
          name: 'auto_advance',
          type: 'boolean',
          label: 'Auto Advance',
          description: 'Automatically finalize the invoice',
          required: false,
          defaultValue: true,
          inBody: true,
        },
      ],
      returns: '$.id, $.customer, $.status, $.total, $.invoice_pdf',
    },
  ],

  triggers: [
    {
      name: 'charge_succeeded',
      description: 'Triggered when a charge is successful',
      eventType: 'charge.succeeded',
      payloadSchema: {
        id: 'string',
        object: 'string',
        amount: 'number',
        currency: 'string',
        status: 'string',
        customer: 'string?',
        receipt_url: 'string',
        payment_method: 'string',
        created: 'number',
      },
      examplePayload: {
        id: 'ch_00000000000000',
        object: 'charge',
        amount: 1000,
        currency: 'usd',
        status: 'succeeded',
        customer: 'cus_00000000000000',
        receipt_url: 'https://pay.stripe.com/receipts/...',
        payment_method: 'pm_00000000000000',
        created: 1705312800,
      },
    },
    {
      name: 'charge_failed',
      description: 'Triggered when a charge fails',
      eventType: 'charge.failed',
      payloadSchema: {
        id: 'string',
        object: 'string',
        amount: 'number',
        currency: 'string',
        status: 'string',
        failure_message: 'string?',
        failure_code: 'string?',
        customer: 'string?',
        created: 'number',
      },
    },
    {
      name: 'invoice_payment_succeeded',
      description: 'Triggered when an invoice payment succeeds',
      eventType: 'invoice.payment_succeeded',
      payloadSchema: {
        id: 'string',
        object: 'string',
        customer: 'string',
        subscription: 'string?',
        amount_paid: 'number',
        status: 'string',
        created: 'number',
      },
    },
    {
      name: 'invoice_payment_failed',
      description: 'Triggered when an invoice payment fails',
      eventType: 'invoice.payment_failed',
      payloadSchema: {
        id: 'string',
        object: 'string',
        customer: 'string',
        subscription: 'string?',
        amount_due: 'number',
        next_payment_attempt: 'number?',
        created: 'number',
      },
    },
    {
      name: 'customer_subscription_created',
      description: 'Triggered when a subscription is created',
      eventType: 'customer.subscription.created',
      payloadSchema: {
        id: 'string',
        object: 'string',
        customer: 'string',
        status: 'string',
        current_period_start: 'number',
        current_period_end: 'number',
        items: 'object',
        created: 'number',
      },
    },
    {
      name: 'customer_subscription_deleted',
      description: 'Triggered when a subscription is canceled',
      eventType: 'customer.subscription.deleted',
      payloadSchema: {
        id: 'string',
        object: 'string',
        customer: 'string',
        status: 'string',
        canceled_at: 'number',
        created: 'number',
      },
    },
    {
      name: 'refund_created',
      description: 'Triggered when a refund is created',
      eventType: 'charge.refunded',
      payloadSchema: {
        id: 'string',
        object: 'string',
        amount: 'number',
        currency: 'string',
        status: 'string',
        refunds: 'object',
        created: 'number',
      },
    },
    {
      name: 'payment_intent_succeeded',
      description: 'Triggered when a payment intent succeeds',
      eventType: 'payment_intent.succeeded',
      payloadSchema: {
        id: 'string',
        object: 'string',
        amount: 'number',
        currency: 'string',
        status: 'string',
        customer: 'string?',
        charges: 'object',
        created: 'number',
      },
    },
  ],
};
