/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║                         TWILIO CONNECTOR                                  ║
 * ║          Send SMS, make calls, manage phone numbers                      ║
 * ║  Production-hardened: rate limiting, retries, health checks,           ║
 * ║  webhook signature verification, sandbox mode                            ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */

import { ExternalConnectorDefinition } from '../key-cortex-external-connector.types';

export const TwilioConnector: ExternalConnectorDefinition = {
  id: 'twilio',
  name: 'Twilio',
  description: 'Send SMS messages, make voice calls, and manage phone numbers via Twilio',
  category: 'communication',
  authType: 'basic',
  logoUrl: 'https://cdn.keyflow.io/connectors/twilio.svg',
  website: 'https://twilio.com',
  docsUrl: 'https://www.twilio.com/docs/api',
  baseUrl: 'https://api.twilio.com/2010-04-01',
  supportsOAuth: false,
  defaultHeaders: {
    'Content-Type': 'application/x-www-form-urlencoded',
  },

  // ── Legacy rate limit (backward compatibility) ──────────────────────────
  rateLimit: {
    requestsPerWindow: 100,
    windowSeconds: 60,
    burstLimit: 50,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PRODUCTION HARDENING
  // ══════════════════════════════════════════════════════════════════════════

  /** Rate limiting — Twilio: 1/sec for most, 100/min for messages */
  rateLimitHardened: {
    requestsPerSecond: 1,
    requestsPerMinute: 100,
    requestsPerHour: 6000,
    burstAllowance: 50,
  },

  /** Retry configuration with exponential backoff + jitter */
  retryConfig: {
    maxRetries: 3,
    baseDelayMs: 1000,
    maxDelayMs: 30000,
    retryableStatusCodes: [429, 500, 502, 503, 504],
    retryableErrors: ['ECONNRESET', 'ETIMEDOUT', 'ENOTFOUND', 'ECONNREFUSED'],
  },

  /** Timeout configuration */
  timeoutConfig: {
    connectTimeoutMs: 10000,
    requestTimeoutMs: 30000,
    uploadTimeoutMs: 60000,
  },

  /** Health check endpoint */
  healthCheck: {
    endpoint: '/Accounts/{accountSid}.json',
    method: 'GET',
    expectedStatus: 200,
  },

  /** Webhook security — Twilio uses request body signing */
  webhookSecurity: {
    signatureHeader: 'x-twilio-signature',
    signatureAlgorithm: 'hmac-sha256',
    signatureFormat: 'base64',
  },

  /** Required scopes — Twilio uses Basic auth, not OAuth scopes */
  requiredScopes: [],

  /** Sandbox/test endpoints — Twilio test credentials */
  sandboxEndpoints: {
    baseUrl: 'https://api.twilio.com/2010-04-01',
  },

  // ══════════════════════════════════════════════════════════════════════════

  configSchema: [
    {
      name: 'accountSid',
      type: 'string',
      label: 'Account SID',
      description: 'Your Twilio Account SID (starts with AC)',
      required: true,
      placeholder: 'AC...your_account_sid...',
    },
    {
      name: 'authToken',
      type: 'password',
      label: 'Auth Token',
      description: 'Your Twilio Auth Token',
      required: true,
      placeholder: '...your_auth_token...',
      secret: true,
    },
    {
      name: 'fromNumber',
      type: 'string',
      label: 'Default From Number',
      description: 'Default Twilio phone number to send from (E.164 format)',
      required: false,
      placeholder: '+14155551234',
      validationPattern: '^\\+?[0-9]{10,15}$',
    },
    {
      name: 'messagingServiceSid',
      type: 'string',
      label: 'Messaging Service SID',
      description: 'Twilio Messaging Service SID for pooled numbers (starts with MG)',
      required: false,
      placeholder: 'MG...your_messaging_service_sid...',
    },
  ],

  actions: [
    {
      name: 'send_sms',
      description: 'Send an SMS message to a phone number',
      endpoint: '/Accounts/{accountSid}/Messages.json',
      method: 'POST',
      category: 'messaging',
      parameters: [
        {
          name: 'accountSid',
          type: 'string',
          label: 'Account SID',
          description: 'Twilio Account SID',
          required: true,
          inPath: true,
        },
        {
          name: 'To',
          type: 'string',
          label: 'To',
          description: 'Destination phone number in E.164 format',
          required: true,
          inBody: true,
        },
        {
          name: 'From',
          type: 'string',
          label: 'From',
          description: 'Twilio phone number to send from (E.164 format)',
          required: false,
          inBody: true,
        },
        {
          name: 'MessagingServiceSid',
          type: 'string',
          label: 'Messaging Service SID',
          description: 'Messaging Service SID (alternative to From)',
          required: false,
          inBody: true,
        },
        {
          name: 'Body',
          type: 'string',
          label: 'Message Body',
          description: 'The text of the message (max 1600 characters)',
          required: true,
          inBody: true,
        },
        {
          name: 'MediaUrl',
          type: 'string',
          label: 'Media URL',
          description: 'URL of media to include (MMS)',
          required: false,
          inBody: true,
        },
        {
          name: 'StatusCallback',
          type: 'url',
          label: 'Status Callback URL',
          description: 'URL to receive delivery status webhooks',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.sid, $.to, $.from, $.body, $.status, $.date_created',
      examplePayload: {
        To: '+14155556789',
        From: '+14155551234',
        Body: 'Hello from KeyFlowOS!',
      },
    },
    {
      name: 'send_bulk_sms',
      description: 'Send the same SMS to multiple recipients',
      endpoint: '/Accounts/{accountSid}/Messages.json',
      method: 'POST',
      category: 'messaging',
      parameters: [
        {
          name: 'accountSid',
          type: 'string',
          label: 'Account SID',
          description: 'Twilio Account SID',
          required: true,
          inPath: true,
        },
        {
          name: 'recipients',
          type: 'json',
          label: 'Recipients',
          description: 'Array of {To, From?, Body, MediaUrl?} objects',
          required: true,
          inBody: true,
        },
        {
          name: 'MessagingServiceSid',
          type: 'string',
          label: 'Messaging Service SID',
          description: 'Messaging Service SID for sending',
          required: false,
          inBody: true,
        },
      ],
      returns: 'Array of message SIDs and statuses',
    },
    {
      name: 'make_call',
      description: 'Initiate an outbound voice call',
      endpoint: '/Accounts/{accountSid}/Calls.json',
      method: 'POST',
      category: 'voice',
      parameters: [
        {
          name: 'accountSid',
          type: 'string',
          label: 'Account SID',
          description: 'Twilio Account SID',
          required: true,
          inPath: true,
        },
        {
          name: 'To',
          type: 'string',
          label: 'To',
          description: 'Phone number to call (E.164 format)',
          required: true,
          inBody: true,
        },
        {
          name: 'From',
          type: 'string',
          label: 'From',
          description: 'Twilio phone number to call from (E.164 format)',
          required: true,
          inBody: true,
        },
        {
          name: 'Url',
          type: 'url',
          label: 'TwiML URL',
          description: 'URL that returns TwiML instructions for the call',
          required: true,
          inBody: true,
        },
        {
          name: 'Method',
          type: 'string',
          label: 'HTTP Method',
          description: 'HTTP method to fetch TwiML',
          required: false,
          defaultValue: 'POST',
          inBody: true,
          options: [
            { label: 'POST', value: 'POST' },
            { label: 'GET', value: 'GET' },
          ],
        },
        {
          name: 'StatusCallback',
          type: 'url',
          label: 'Status Callback URL',
          description: 'URL to receive call status events',
          required: false,
          inBody: true,
        },
        {
          name: 'Record',
          type: 'boolean',
          label: 'Record Call',
          description: 'Whether to record the call',
          required: false,
          defaultValue: false,
          inBody: true,
        },
        {
          name: 'Timeout',
          type: 'number',
          label: 'Timeout',
          description: 'Seconds to wait for answer (max 60)',
          required: false,
          defaultValue: 30,
          inBody: true,
        },
      ],
      returns: '$.sid, $.to, $.from, $.status, $.date_created, $.uri',
      examplePayload: {
        To: '+14155556789',
        From: '+14155551234',
        Url: 'https://handler.twilio.com/twiml/...',
        Timeout: 30,
      },
    },
    {
      name: 'get_messages',
      description: 'List sent and received messages',
      endpoint: '/Accounts/{accountSid}/Messages.json',
      method: 'GET',
      category: 'messaging',
      parameters: [
        {
          name: 'accountSid',
          type: 'string',
          label: 'Account SID',
          description: 'Twilio Account SID',
          required: true,
          inPath: true,
        },
        {
          name: 'To',
          type: 'string',
          label: 'To',
          description: 'Filter by destination number',
          required: false,
          inQuery: true,
        },
        {
          name: 'From',
          type: 'string',
          label: 'From',
          description: 'Filter by sender number',
          required: false,
          inQuery: true,
        },
        {
          name: 'DateSent>',
          type: 'string',
          label: 'Sent After',
          description: 'Filter messages sent on or after (YYYY-MM-DD)',
          required: false,
          inQuery: true,
        },
        {
          name: 'DateSent<',
          type: 'string',
          label: 'Sent Before',
          description: 'Filter messages sent on or before (YYYY-MM-DD)',
          required: false,
          inQuery: true,
        },
        {
          name: 'PageSize',
          type: 'number',
          label: 'Page Size',
          description: 'Number of results per page (1-1000)',
          required: false,
          defaultValue: 50,
          inQuery: true,
        },
        {
          name: 'Page',
          type: 'number',
          label: 'Page Number',
          description: 'Page number to retrieve',
          required: false,
          inQuery: true,
        },
      ],
      returns: '$.messages[*].sid, $.messages[*].to, $.messages[*].from, $.messages[*].body, $.messages[*].status',
    },
    {
      name: 'get_message',
      description: 'Retrieve a single message by SID',
      endpoint: '/Accounts/{accountSid}/Messages/{messageSid}.json',
      method: 'GET',
      category: 'messaging',
      parameters: [
        {
          name: 'accountSid',
          type: 'string',
          label: 'Account SID',
          description: 'Twilio Account SID',
          required: true,
          inPath: true,
        },
        {
          name: 'messageSid',
          type: 'string',
          label: 'Message SID',
          description: 'SID of the message to retrieve',
          required: true,
          inPath: true,
        },
      ],
      returns: '$.sid, $.to, $.from, $.body, $.status, $.date_created, $.price',
    },
    {
      name: 'buy_number',
      description: 'Purchase a new phone number',
      endpoint: '/Accounts/{accountSid}/IncomingPhoneNumbers.json',
      method: 'POST',
      category: 'phone_numbers',
      parameters: [
        {
          name: 'accountSid',
          type: 'string',
          label: 'Account SID',
          description: 'Twilio Account SID',
          required: true,
          inPath: true,
        },
        {
          name: 'PhoneNumber',
          type: 'string',
          label: 'Phone Number',
          description: 'Exact phone number to purchase (E.164)',
          required: false,
          inBody: true,
        },
        {
          name: 'AreaCode',
          type: 'string',
          label: 'Area Code',
          description: 'Area code to search for available numbers',
          required: false,
          inBody: true,
        },
        {
          name: 'FriendlyName',
          type: 'string',
          label: 'Friendly Name',
          description: 'Human-readable name for this number',
          required: false,
          inBody: true,
        },
        {
          name: 'SmsUrl',
          type: 'url',
          label: 'SMS URL',
          description: 'URL for incoming SMS webhooks',
          required: false,
          inBody: true,
        },
        {
          name: 'VoiceUrl',
          type: 'url',
          label: 'Voice URL',
          description: 'URL for incoming voice call webhooks',
          required: false,
          inBody: true,
        },
      ],
      returns: '$.sid, $.phone_number, $.friendly_name, $.date_created, $.capabilities',
    },
    {
      name: 'list_numbers',
      description: 'List all purchased phone numbers',
      endpoint: '/Accounts/{accountSid}/IncomingPhoneNumbers.json',
      method: 'GET',
      category: 'phone_numbers',
      parameters: [
        {
          name: 'accountSid',
          type: 'string',
          label: 'Account SID',
          description: 'Twilio Account SID',
          required: true,
          inPath: true,
        },
        {
          name: 'PhoneNumber',
          type: 'string',
          label: 'Phone Number Filter',
          description: 'Filter by phone number',
          required: false,
          inQuery: true,
        },
        {
          name: 'FriendlyName',
          type: 'string',
          label: 'Friendly Name Filter',
          description: 'Filter by friendly name',
          required: false,
          inQuery: true,
        },
        {
          name: 'PageSize',
          type: 'number',
          label: 'Page Size',
          description: 'Number of results per page',
          required: false,
          defaultValue: 50,
          inQuery: true,
        },
      ],
      returns: '$.incoming_phone_numbers[*].sid, $.incoming_phone_numbers[*].phone_number, $.incoming_phone_numbers[*].friendly_name',
    },
    {
      name: 'release_number',
      description: 'Release a purchased phone number',
      endpoint: '/Accounts/{accountSid}/IncomingPhoneNumbers/{phoneNumberSid}.json',
      method: 'DELETE',
      category: 'phone_numbers',
      parameters: [
        {
          name: 'accountSid',
          type: 'string',
          label: 'Account SID',
          description: 'Twilio Account SID',
          required: true,
          inPath: true,
        },
        {
          name: 'phoneNumberSid',
          type: 'string',
          label: 'Phone Number SID',
          description: 'SID of the phone number to release',
          required: true,
          inPath: true,
        },
      ],
      returns: 'true on success',
    },
    {
      name: 'get_call_logs',
      description: 'List call logs',
      endpoint: '/Accounts/{accountSid}/Calls.json',
      method: 'GET',
      category: 'voice',
      parameters: [
        {
          name: 'accountSid',
          type: 'string',
          label: 'Account SID',
          description: 'Twilio Account SID',
          required: true,
          inPath: true,
        },
        {
          name: 'To',
          type: 'string',
          label: 'To',
          description: 'Filter by called number',
          required: false,
          inQuery: true,
        },
        {
          name: 'From',
          type: 'string',
          label: 'From',
          description: 'Filter by caller number',
          required: false,
          inQuery: true,
        },
        {
          name: 'Status',
          type: 'string',
          label: 'Status',
          description: 'Filter by call status',
          required: false,
          inQuery: true,
          options: [
            { label: 'Queued', value: 'queued' },
            { label: 'Ringing', value: 'ringing' },
            { label: 'In Progress', value: 'in-progress' },
            { label: 'Completed', value: 'completed' },
            { label: 'Busy', value: 'busy' },
            { label: 'Failed', value: 'failed' },
            { label: 'No Answer', value: 'no-answer' },
            { label: 'Canceled', value: 'canceled' },
          ],
        },
        {
          name: 'StartTime>',
          type: 'string',
          label: 'Started After',
          description: 'Filter calls started on or after (YYYY-MM-DD)',
          required: false,
          inQuery: true,
        },
        {
          name: 'PageSize',
          type: 'number',
          label: 'Page Size',
          description: 'Number of results per page',
          required: false,
          defaultValue: 50,
          inQuery: true,
        },
      ],
      returns: '$.calls[*].sid, $.calls[*].to, $.calls[*].from, $.calls[*].status, $.calls[*].duration',
    },
  ],

  triggers: [
    {
      name: 'sms_received',
      description: 'Triggered when an incoming SMS is received',
      eventType: 'sms.received',
      payloadSchema: {
        MessageSid: 'string',
        From: 'string',
        To: 'string',
        Body: 'string',
        NumMedia: 'string',
        MediaUrl0: 'string?',
        FromCity: 'string?',
        FromState: 'string?',
        FromCountry: 'string?',
      },
      examplePayload: {
        MessageSid: 'SM00000000000000000000000000000000',
        From: '+14155556789',
        To: '+14155551234',
        Body: 'Hello!',
        NumMedia: '0',
        FromCity: 'SAN FRANCISCO',
        FromState: 'CA',
        FromCountry: 'US',
      },
    },
    {
      name: 'call_received',
      description: 'Triggered when an incoming call is received',
      eventType: 'call.received',
      payloadSchema: {
        CallSid: 'string',
        From: 'string',
        To: 'string',
        CallStatus: 'string',
        Direction: 'string',
        FromCity: 'string?',
        FromState: 'string?',
        FromCountry: 'string?',
      },
    },
    {
      name: 'message_status_updated',
      description: 'Triggered when a message status changes',
      eventType: 'message.status',
      payloadSchema: {
        MessageSid: 'string',
        MessageStatus: 'string',
        To: 'string',
        From: 'string',
        ErrorCode: 'string?',
      },
    },
    {
      name: 'call_status_updated',
      description: 'Triggered when a call status changes',
      eventType: 'call.status',
      payloadSchema: {
        CallSid: 'string',
        CallStatus: 'string',
        To: 'string',
        From: 'string',
        CallDuration: 'string?',
        RecordingUrl: 'string?',
      },
    },
    {
      name: 'recording_completed',
      description: 'Triggered when a call recording is completed',
      eventType: 'recording.completed',
      payloadSchema: {
        RecordingSid: 'string',
        CallSid: 'string',
        RecordingUrl: 'string',
        RecordingDuration: 'string',
        RecordingStatus: 'string',
      },
      isPremium: true,
    },
  ],
};
