export interface RecommendationTemplate {
  id: string;
  title: string;
  description: string;
  category: 'clarity' | 'pricing' | 'legal' | 'operations' | 'sales' | 'retention' | 'compliance' | 'growth';
  impactLevel: 'high' | 'medium' | 'low';
  estimatedDifficulty: 'easy' | 'moderate' | 'hard';
  rationale: string;
  suggestedAction: string;
  triggerScoreKey: string;
  triggerThreshold: number;
  businessTypeRelevance: string[];
  stageRelevance: string[];
}

export const RECOMMENDATION_TEMPLATES: RecommendationTemplate[] = [
  {
    id: 'clarify_offer',
    title: 'Clarify Your Core Offer',
    description: 'Your value proposition lacks clarity. Customers need to understand exactly what you offer, who it is for, and why it matters within seconds.',
    category: 'clarity',
    impactLevel: 'high',
    estimatedDifficulty: 'moderate',
    rationale: 'Businesses with unclear offers struggle to convert interest into revenue. A sharp offer statement is the foundation of every marketing and sales effort.',
    suggestedAction: 'Write a one-sentence offer statement: "I help [specific customer] achieve [specific outcome] through [your method]." Test it with 5 people — if they can repeat it back, you have clarity.',
    triggerScoreKey: 'offerClarity',
    triggerThreshold: 60,
    businessTypeRelevance: ['service', 'saas', 'agency', 'clinic', 'ecommerce'],
    stageRelevance: ['idea', 'pre_launch', 'newly_launched'],
  },
  {
    id: 'narrow_customer_segment',
    title: 'Narrow Your Customer Segment',
    description: 'You are targeting too broad an audience. Narrowing your ideal customer profile (ICP) will improve conversion rates and reduce wasted marketing spend.',
    category: 'clarity',
    impactLevel: 'high',
    estimatedDifficulty: 'moderate',
    rationale: 'Trying to serve everyone dilutes your messaging, pricing, and product development. The most successful small businesses dominate a niche before expanding.',
    suggestedAction: 'Define your ICP with demographics, pain points, and buying triggers. Focus all marketing on this segment for the next 90 days and measure conversion improvements.',
    triggerScoreKey: 'customerClarity',
    triggerThreshold: 60,
    businessTypeRelevance: ['service', 'saas', 'agency', 'ecommerce'],
    stageRelevance: ['idea', 'pre_launch', 'newly_launched', 'operating'],
  },
  {
    id: 'revise_pricing',
    title: 'Revise Your Pricing Strategy',
    description: 'Your pricing may not reflect the value you deliver or cover your true costs. Underpricing is one of the most common mistakes in early-stage businesses.',
    category: 'pricing',
    impactLevel: 'high',
    estimatedDifficulty: 'moderate',
    rationale: 'Incorrect pricing directly impacts profitability, cash flow, and business sustainability. Value-based pricing typically yields 20-40% higher revenue than cost-plus pricing.',
    suggestedAction: 'Calculate your true cost per delivery (including your time), research competitor pricing, and set prices based on the value and outcome you provide — not just your costs.',
    triggerScoreKey: 'pricingScore',
    triggerThreshold: 60,
    businessTypeRelevance: ['service', 'saas', 'agency', 'clinic', 'ecommerce'],
    stageRelevance: ['pre_launch', 'newly_launched', 'operating'],
  },
  {
    id: 'reduce_costs',
    title: 'Reduce Operating Costs',
    description: 'Your cost structure is eating into margins. Identify and eliminate unnecessary expenses to improve profitability without reducing revenue.',
    category: 'pricing',
    impactLevel: 'medium',
    estimatedDifficulty: 'moderate',
    rationale: 'High operating costs reduce runway, limit reinvestment, and increase the revenue needed to break even. Many businesses can cut 15-25% of costs without impacting quality.',
    suggestedAction: 'Audit every recurring expense. Categorize as essential, nice-to-have, or unnecessary. Eliminate the unnecessary, negotiate better rates on essentials, and defer nice-to-haves.',
    triggerScoreKey: 'costEfficiency',
    triggerThreshold: 50,
    businessTypeRelevance: ['service', 'saas', 'agency', 'clinic', 'ecommerce'],
    stageRelevance: ['operating', 'growing', 'mature'],
  },
  {
    id: 'formalize_registration',
    title: 'Formalize Business Registration',
    description: 'Your business registration and legal structure need attention. Operating without proper registration exposes you to legal and financial risk.',
    category: 'legal',
    impactLevel: 'high',
    estimatedDifficulty: 'easy',
    rationale: 'Proper registration protects personal assets, enables formal banking relationships, qualifies you for contracts and grants, and builds customer trust.',
    suggestedAction: 'Register your business with the appropriate government authority (e.g., Companies Registry). Choose the right structure (sole trader, LLC, or limited company) based on liability and tax implications.',
    triggerScoreKey: 'legalCompliance',
    triggerThreshold: 50,
    businessTypeRelevance: ['service', 'saas', 'agency', 'clinic', 'ecommerce'],
    stageRelevance: ['idea', 'pre_launch', 'newly_launched'],
  },
  {
    id: 'improve_tax_setup',
    title: 'Improve Tax and Accounting Setup',
    description: 'Your tax and accounting systems need improvement. Poor financial record-keeping leads to compliance issues and missed tax optimization opportunities.',
    category: 'legal',
    impactLevel: 'medium',
    estimatedDifficulty: 'moderate',
    rationale: 'Proper tax setup prevents penalties, enables deductions, provides accurate financial visibility, and simplifies year-end filing.',
    suggestedAction: 'Set up a dedicated business bank account, implement expense tracking, register for applicable taxes (VAT/sales tax), and schedule quarterly reviews with an accountant.',
    triggerScoreKey: 'taxSetup',
    triggerThreshold: 50,
    businessTypeRelevance: ['service', 'saas', 'agency', 'clinic', 'ecommerce'],
    stageRelevance: ['pre_launch', 'newly_launched', 'operating'],
  },
  {
    id: 'open_bank_account',
    title: 'Open a Dedicated Business Bank Account',
    description: 'Mixing personal and business finances creates confusion, complicates taxes, and limits your ability to track true business performance.',
    category: 'legal',
    impactLevel: 'medium',
    estimatedDifficulty: 'easy',
    rationale: 'A separate business account is foundational for accurate bookkeeping, tax compliance, and professional credibility with clients and vendors.',
    suggestedAction: 'Open a business bank account at your preferred bank. Set up automatic transfers for tax reserves (set aside 25-30% of revenue). Route all business income and expenses through this account.',
    triggerScoreKey: 'financialSetup',
    triggerThreshold: 40,
    businessTypeRelevance: ['service', 'saas', 'agency', 'clinic', 'ecommerce'],
    stageRelevance: ['idea', 'pre_launch', 'newly_launched'],
  },
  {
    id: 'build_onboarding_process',
    title: 'Build a Client Onboarding Process',
    description: 'You lack a structured onboarding process for new clients or customers. This leads to inconsistent experiences, scope creep, and delayed value delivery.',
    category: 'operations',
    impactLevel: 'high',
    estimatedDifficulty: 'moderate',
    rationale: 'A consistent onboarding process reduces churn by 30-50%, sets clear expectations, and creates a professional first impression that drives referrals.',
    suggestedAction: 'Map your ideal first-week client experience. Create a welcome email sequence, intake form, kickoff checklist, and communication schedule. Automate where possible.',
    triggerScoreKey: 'onboardingProcess',
    triggerThreshold: 50,
    businessTypeRelevance: ['service', 'agency', 'clinic', 'saas'],
    stageRelevance: ['newly_launched', 'operating', 'growing'],
  },
  {
    id: 'create_workflow_documentation',
    title: 'Document Core Business Workflows',
    description: 'Your key processes are not documented, making your business dependent on memory and individual knowledge. This limits growth and delegation.',
    category: 'operations',
    impactLevel: 'medium',
    estimatedDifficulty: 'moderate',
    rationale: 'Documented workflows enable delegation, maintain quality consistency, reduce training time for new team members, and identify optimization opportunities.',
    suggestedAction: 'List your 5 most repeated processes. For each, document: trigger, steps, tools used, expected outcome, and who is responsible. Start with the highest-volume process.',
    triggerScoreKey: 'workflowMaturity',
    triggerThreshold: 50,
    businessTypeRelevance: ['service', 'agency', 'clinic', 'ecommerce'],
    stageRelevance: ['operating', 'growing', 'mature'],
  },
  {
    id: 'define_lead_generation_channel',
    title: 'Define a Lead Generation Channel',
    description: 'You do not have a consistent, reliable source of new leads. Without predictable lead flow, revenue becomes unpredictable.',
    category: 'sales',
    impactLevel: 'high',
    estimatedDifficulty: 'moderate',
    rationale: 'Businesses that rely on word-of-mouth alone hit a growth ceiling. At least one scalable lead channel is essential for sustainable growth.',
    suggestedAction: 'Choose one primary lead channel (social media, content marketing, referral program, paid ads, or partnerships). Commit to it for 90 days with weekly tracking of leads generated.',
    triggerScoreKey: 'leadGeneration',
    triggerThreshold: 50,
    businessTypeRelevance: ['service', 'saas', 'agency', 'clinic', 'ecommerce'],
    stageRelevance: ['newly_launched', 'operating', 'growing'],
  },
  {
    id: 'build_sales_pipeline',
    title: 'Build a Sales Pipeline',
    description: 'You lack visibility into your sales process. Without a pipeline, you cannot forecast revenue, identify bottlenecks, or prioritize high-value opportunities.',
    category: 'sales',
    impactLevel: 'high',
    estimatedDifficulty: 'moderate',
    rationale: 'A structured pipeline provides revenue predictability, helps prioritize effort, and reveals where deals stall — enabling targeted improvements.',
    suggestedAction: 'Define your sales stages (e.g., Lead → Qualified → Proposal → Negotiation → Closed). Track every opportunity through these stages. Review pipeline weekly and calculate conversion rates between stages.',
    triggerScoreKey: 'salesProcess',
    triggerThreshold: 50,
    businessTypeRelevance: ['service', 'saas', 'agency'],
    stageRelevance: ['newly_launched', 'operating', 'growing'],
  },
  {
    id: 'create_retention_strategy',
    title: 'Create a Customer Retention Strategy',
    description: 'You are focused on acquisition but neglecting retention. Retaining existing customers is 5-7x cheaper than acquiring new ones and drives long-term profitability.',
    category: 'retention',
    impactLevel: 'high',
    estimatedDifficulty: 'moderate',
    rationale: 'Increasing retention by just 5% can increase profits by 25-95%. Repeat customers also spend more and refer others, compounding growth.',
    suggestedAction: 'Implement at least one retention tactic: regular check-in emails, loyalty rewards, feedback surveys, or exclusive offers for existing customers. Measure repeat purchase rate monthly.',
    triggerScoreKey: 'retentionScore',
    triggerThreshold: 50,
    businessTypeRelevance: ['service', 'saas', 'clinic', 'ecommerce'],
    stageRelevance: ['operating', 'growing', 'mature'],
  },
  {
    id: 'improve_data_privacy_compliance',
    title: 'Improve Data Privacy Compliance',
    description: 'Your handling of customer data may not meet privacy requirements. Data breaches and non-compliance can result in fines and lost customer trust.',
    category: 'compliance',
    impactLevel: 'medium',
    estimatedDifficulty: 'moderate',
    rationale: 'Data privacy regulations are expanding globally. Proactive compliance protects your business from legal action and builds customer confidence.',
    suggestedAction: 'Audit what customer data you collect and store. Create a privacy policy. Implement consent mechanisms for data collection. Ensure secure storage and limit access to sensitive data.',
    triggerScoreKey: 'dataPrivacy',
    triggerThreshold: 60,
    businessTypeRelevance: ['saas', 'ecommerce', 'clinic'],
    stageRelevance: ['newly_launched', 'operating', 'growing', 'mature'],
  },
  {
    id: 'reduce_founder_dependency',
    title: 'Reduce Founder Dependency',
    description: 'Your business cannot function without you. This limits growth, creates burnout risk, and makes the business unsellable or fragile.',
    category: 'operations',
    impactLevel: 'high',
    estimatedDifficulty: 'hard',
    rationale: 'Founder-dependent businesses hit a ceiling. Delegation, documentation, and systems are required to scale beyond what one person can manage.',
    suggestedAction: 'Identify the 3 tasks only you currently do. For each, create a documented process and train or hire someone to take it over. Start with the most time-consuming task.',
    triggerScoreKey: 'founderDependency',
    triggerThreshold: 60,
    businessTypeRelevance: ['service', 'agency', 'clinic'],
    stageRelevance: ['operating', 'growing', 'mature'],
  },
  {
    id: 'formalize_contracts',
    title: 'Formalize Client Contracts',
    description: 'You operate without formal agreements. This exposes you to scope creep, payment disputes, and legal liability.',
    category: 'legal',
    impactLevel: 'high',
    estimatedDifficulty: 'moderate',
    rationale: 'Formal contracts protect both parties, set clear expectations, define payment terms, and provide legal recourse if disputes arise.',
    suggestedAction: 'Create a standard service agreement template covering: scope of work, deliverables, timelines, payment terms, cancellation policy, and liability limits. Have it reviewed by a legal professional.',
    triggerScoreKey: 'contractFormality',
    triggerThreshold: 50,
    businessTypeRelevance: ['service', 'agency', 'clinic'],
    stageRelevance: ['pre_launch', 'newly_launched', 'operating'],
  },
];

export function getTemplateById(id: string): RecommendationTemplate | undefined {
  return RECOMMENDATION_TEMPLATES.find((t) => t.id === id);
}
