import ts from 'typescript';
import fs from 'fs';
import path from 'path';

const file = path.resolve('apps/web/src/lib/client.ts');
const source = fs.readFileSync(file, 'utf8');
const src = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true);

const domains = {
  crm: [/^fetchContacts/, /^fetchContact/, /^createContact/, /^updateContact/, /^deleteContact/, /^mergeContacts/, /^fetchDuplicateContacts/, /^fetchMergePreview/, /^revertMerge/, /^fetchFavorites/, /^toggleFavorite/, /^fetchCustomField/, /^createCustomField/, /^updateCustomField/, /^archiveCustomField/, /^restoreCustomField/, /^deleteCustomField/, /^fetchContactCustomField/, /^fetchDeal/, /^createDeal/, /^updateDeal/, /^deleteDeal/, /^moveDeal/, /^bulkMoveDeal/, /^winDeal/, /^loseDeal/, /^fetchDealForecast/, /^fetchDealVelocity/, /^fetchWonLost/, /^createWonLost/, /^updateWonLost/, /^deleteWonLost/, /^fetchAccount/, /^createAccount/, /^updateAccount/, /^deleteAccount/, /^suggestAccount/, /^previewAccountMerge/, /^applyAccountMerge/, /^fetchLifecycleByAccount/, /^fetchDealsByAccount/, /^fetchContactDeals/, /^approveAutopilotAction/, /^denyAutopilotAction/, /^fetchContactStats/, /^fetchSegmentSummary/, /^fetchRelationshipHealth/, /^updateRelationshipHealth/, /^recomputeRelationshipHealth/, /^setContactRelationshipHealth/, /^clearContactRelationshipHealth/, /^fetchAtRiskContacts/, /^fetchCrmHighlights/, /^fetchContactNextActions/, /^completeContactNextAction/, /^snoozeContactNextAction/, /^fetchDueTasks/, /^bulkUpdateContacts/, /^bulkDeleteContacts/, /^bulkReassignContacts/, /^fetchTeamMembers/, /^checkImportDuplicates/, /^fetchImportJobs/, /^importContacts/, /^getGoogleContactsAuthUrl/, /^createContactFromOcr/, /^scanContactImage/, /^completeContactTask/, /^reopenContactTask/, /^fetchContactEvents/, /^fetchContactNotes/, /^fetchContactTasks/, /^fetchBestChannelExplain/, /^fetchContactPlaybook/, /^updateContactPlaybook/, /^logContactEvent/, /^logCommunication/, /^addContactNote/, /^addContactTask/, /^updateContactNote/, /^deleteContactNote/, /^updateContactTask/, /^deleteContactTask/, /^fetchContactRevenueSummary/, /^fetchContactInsightSnapshot/, /^recomputeContactInsightSnapshot/, /^fetchActivityFeed/, /^fetchContactHealthMetrics/, /^fetchContactDossier/, /^fetchContactJourney/, /^fetchContactCrossJourney/, /^fetchPredictiveRevenue/, /^fetchConversationContext/, /^generateAiInsight/, /^fetchContactRelationships/, /^fetchContactNetwork/, /^fetchNetworkGraph/, /^createContactRelationship/, /^deleteContactRelationship/, /^referContact/, /^fetchDataQuality/, /^runDataQuality/, /^applyDataQuality/, /^dismissDataQuality/, /^bulkApplyDataQuality/, /^updateDataQualitySettings/, /^fetchUnreadCounts/, /^sendContactReply/, /^fetchConversationSummary/, /^regenerateConversationSummary/, /^fetchSuggestedReplies/, /^fetchConversationInsights/, /^markContactConversationsRead/],
  commerce: [/^fetchProducts/, /^createProduct/, /^updateProduct/, /^deleteProduct/, /^bulkUpdateProducts/, /^fetchInvoices/, /^getInvoice/, /^createInvoice/, /^updateInvoice/, /^deleteInvoice/, /^bulkUpdateInvoices/, /^updateInvoiceStatus/, /^markInvoicePaid/, /^recordInvoicePayment/, /^recordPaymentFromEvidence/, /^extractPaymentEvidence/, /^listInvoicePayments/, /^getInvoiceTimeline/, /^createInvoicePaymentLink/, /^sendInvoiceEmail/, /^sendInvoiceReminder/, /^resendInvoiceReceipt/, /^getPublicInvoiceByToken/, /^listQuotes/, /^getQuote/, /^createQuote/, /^updateQuote/, /^deleteQuote/, /^bulkUpdateQuotes/, /^updateQuoteStatus/, /^convertQuoteToInvoice/, /^getGmailAuthUrl/, /^getGmailStatus/, /^disconnectGmail/, /^sendQuoteEmail/, /^fetchStaleQuotes/, /^sendStaleQuoteFollowUp/, /^fetchPublicQuote/, /^acceptPublicQuote/, /^rejectPublicQuote/, /^fetchBookings/, /^createBooking/, /^rescheduleBooking/, /^updateBookingNotes/, /^updateBookingLocation/, /^fetchReminderSettings/, /^updateReminderSettings/, /^fetchStaffAvailability/, /^setStaffAvailability/, /^fetchStaff/, /^createStaff/, /^deleteStaff/, /^fetchServices/, /^createService/, /^updateService/, /^deleteService/, /^syncBookingToCalendar/, /^createInvoiceFromBooking/, /^fetchBookingStats/, /^fetchScheduleHealth/, /^fetchCockpitSummary/, /^fetchTodaysTasks/, /^fetchAllAutopilotTasks/, /^updateAutopilotTaskStatus/, /^approveAutopilotTask/, /^denyAutopilotTask/, /^generateAutopilotDraft/, /^executeAutopilotAction/, /^fetchAutopilotSettings/, /^updateAutopilotSettings/, /^fetchAutopilotStats/, /^fetchCriticalAlerts/, /^generateSetupTasks/, /^fetchMomentumRecommendations/, /^actionMomentumRecommendation/, /^snoozeMomentumRecommendation/, /^dismissMomentumRecommendation/, /^generateMomentumDraft/, /^fetchContactMomentum/, /^fetchContactMomentumHistory/, /^fetchMomentumSummary/, /^triggerMomentumSweep/, /^fetchConversionFunnel/, /^fetchProductHealth/, /^fetchSeoHealth/, /^fetchConversionSuggestions/, /^fetchAiConversionAdvice/, /^PAYMENT_METHODS/, /^fetchRecurringInvoices/, /^createRecurringInvoice/, /^updateRecurringInvoice/, /^deleteRecurringInvoice/, /^toggleRecurringInvoice/, /^cancelRecurringInvoice/, /^fetchRecurringGenerationHistory/, /^fetchSlowPayers/, /^fetchPricingSignals/, /^fetchRevenueActions/, /^fetchRevenueOverview/, /^reconcileRevenueActions/, /^completeRevenueAction/, /^dismissRevenueAction/, /^snoozeRevenueAction/, /^fetchCommerceRevenueForecast/, /^fetchRevenueBriefing/, /^regenerateRevenueBriefing/, /^delegateRevenueBriefingChase/, /^fetchRevenueReport/, /^sendAccountantExportEmail/, /^getStorefrontVisitorId/, /^getStorefrontReferralCode/, /^trackStoreEvent/, /^backfillStoreLinks/, /^fetchStorefrontConfig/, /^updateStorefrontConfig/, /^fetchStoreAnalytics/, /^fetchStoreGraph/, /^fetchStoreReadiness/, /^fetchProductHealth/, /^fetchConversionFunnel/, /^fetchConversionSuggestions/, /^fetchAiConversionAdvice/],
  finance: [/^fetchExpenses/, /^getExpense/, /^createExpense/, /^updateExpense/, /^deleteExpense/, /^fetchExpenseCategories/, /^createExpenseCategory/, /^deleteExpenseCategory/, /^fetchExpenseSummary/, /^fetchMarginAnalysis/, /^fetchExpensesByProject/, /^fetchExpensesByService/, /^fetchRecurringCandidates/, /^fetchRecurringExpenses/, /^createRecurringExpense/, /^updateRecurringExpense/, /^cancelRecurringExpense/, /^runRecurringExpenseNow/, /^fetchVendorAnalytics/, /^fetchExpenseBudgets/, /^upsertExpenseBudget/, /^deleteExpenseBudget/, /^getExpenseExportUrl/, /^fetchBusinessPayments/, /^fetchPaymentsGateways/, /^fetchPaymentsTransactions/, /^fetchPaymentsLinks/, /^createPaymentsLink/, /^revokePaymentsLink/, /^refundPaymentsCharge/, /^fetchTransactionLink/, /^fetchAccountingSummary/, /^fetchUnsyncedInvoices/, /^pushInvoicesToAccounting/, /^pushCustomersToAccounting/, /^fetchChartOfAccounts/, /^fetchFinanceOverview/, /^fetchFinanceIntelActions/, /^runFinanceIntelScan/, /^resolveFinanceIntelAction/, /^dismissFinanceIntelAction/, /^fetchFinanceInsightStrip/, /^fetchFinanceAccounts/, /^createFinanceAccount/, /^updateFinanceAccount/, /^archiveFinanceAccount/, /^fetchFinanceCoa/, /^createFinanceCoa/, /^updateFinanceCoa/, /^archiveFinanceCoa/, /^fetchJournalEntries/, /^createJournalEntry/, /^extractReceipt/, /^fetchTaxRates/, /^createTaxRate/, /^updateTaxRate/, /^deleteTaxRate/, /^fetchFinanceSettings/, /^updateFinanceSettings/, /^fetchTaxLiabilities/, /^recomputeTaxLiabilities/, /^fetchTaxLiability/, /^fetchTaxContributingInvoices/, /^fileTaxLiability/, /^payTaxLiability/, /^downloadAccountantExport/],
  identity: [/^bootstrapIdentity/, /^identitySignup/, /^identityLogin/, /^identityResendVerification/, /^fetchMe/, /^getBusinessById/, /^updateBusiness/],
  social: [/^fetchPosts/, /^postNow/, /^schedulePost/, /^fetchRecentExternalPosts/, /^createPost/, /^updatePost/, /^deletePost/, /^publishPost/, /^fetchSocialConnections/, /^startSocialOAuth/, /^completeSocialOAuth/, /^fetchOAuthAvailability/, /^connectSocialManual/, /^disconnectSocial/, /^testSocialConnection/, /^fetchSocialAnalytics/, /^fetchAccountMetrics/, /^fetchMarketingLists/, /^pushContactsToMarketingList/, /^fetchMarketingCampaigns/, /^triggerMarketingCampaign/],
  projects: [/^fetchProjects/, /^createProject/, /^updateProject/, /^deleteProject/, /^createProjectTask/, /^updateProjectTask/, /^deleteProjectTask/, /^fetchProjectTemplates/, /^createProjectTemplate/, /^deleteProjectTemplate/, /^createProjectFromTemplate/, /^fetchSupportTickets/, /^createSupportTicket/, /^updateSupportTicket/, /^deleteSupportTicket/],
  calendar: [/^getCalendarAuthUrl/, /^getCalendarStatus/, /^disconnectCalendar/, /^fetchGoogleCalendarEvents/, /^updateBookingStatus/, /^fetchCalendarEvents/, /^fetchCalendarAgenda/, /^fetchCalendarConflicts/, /^fetchCalendarInsights/, /^fetchCalendarDailyPlan/, /^fetchCalendarWeeklyCapacity/, /^createCalendarEvent/, /^patchCalendarEvent/, /^cancelCalendarEvent/],
  ai: [/^fetchPlaybooks/, /^createPlaybook/, /^updatePlaybook/, /^testRunPlaybook/, /^aiGenerateFlow/, /^keyInterpretFlow/, /^keyBuildFlow/, /^keyExecuteFlow/, /^keyTalkFlow/, /^keyInterpretDelegation/, /^keyBuildDelegation/, /^keyExecuteDelegation/, /^keyTalkDelegation/, /^keyInterpretCalendar/, /^keyBuildCalendar/, /^keyExecuteCalendar/, /^keyTalkCalendar/, /^fetchFlowIntelligence/, /^fetchAiNextActions/, /^fetchNextActions/, /^completeNextAction/, /^fetchAutopilotActionsForCrm/, /^aiGenerateDraft/, /^aiRewriteContent/, /^aiSuggestSubjects/, /^aiSuggestCta/, /^aiSuggestHashtags/, /^aiShortenExpand/, /^aiSuggestChannels/, /^aiSuggestSendTime/, /^aiSuggestPreviewText/, /^aiSuggestAudienceSegments/, /^aiSuggestContentIdeas/],
  analytics: [/^fetchAnalyticsOverview/, /^fetchAnalyticsSnapshots/, /^fetchAnalyticsTrends/, /^fetchAnalyticsMetrics/, /^generateRevenueProjection/, /^generateContactProjection/, /^fetchProjections/, /^generateInsights/, /^fetchInsights/, /^markInsightRead/, /^dismissInsight/, /^assessMaturity/, /^fetchLatestMaturity/, /^fetchMaturityHistory/, /^fetchFinancialGrowth/],
  trash: [/^fetchTrashItems/, /^restoreTrashItem/, /^permanentDeleteTrashItem/],
  marketing: [/^listChannelConnections/, /^createChannelConnection/, /^listChannelDestinations/, /^createOutboundContent/, /^updateOutboundContent/, /^listOutboundContent/, /^getOutboundContent/, /^deleteOutboundContent/, /^upsertOutboundVariant/, /^publishContentNow/, /^scheduleContent/, /^rescheduleDelivery/, /^cancelDelivery/, /^retryDelivery/, /^getDeliverySummary/, /^getChannelHealthSummary/, /^runChannelHealthCheck/, /^toggleChannelDestination/, /^updateChannelConnection/, /^deleteChannelConnection/, /^syncChannelConnectionsFromSocial/, /^validateEmailSend/, /^expandAudience/, /^getAudienceHealth/, /^listDeliveries/, /^getDeliveryEvents/, /^retryAllFailedDeliveries/],
  omnichannel: [/^fetchQualificationConfig/, /^updateQualificationConfig/, /^fetchQualificationAnalytics/, /^quoteFromConversation/],
  keyflow: [/^fetchKeyflowEvents/, /^fetchKeyflowNotes/, /^createKeyflowNote/, /^updateKeyflowNote/, /^deleteKeyflowNote/, /^generateKeyflowNoteBrief/, /^synthesizeKeyflowSpeech/, /^transcribeKeyflowSpeech/, /^fetchVoiceSessions/, /^createVoiceSession/, /^endVoiceSession/, /^fetchVoicePreferences/, /^saveVoicePreference/],
  community: [/^listOpportunities/, /^getOpportunity/, /^createOpportunity/, /^listMyOpportunities/, /^updateOpportunity/, /^closeOpportunity/, /^deleteOpportunity/, /^applyToOpportunity/, /^listMyOpportunityApplications/, /^respondToOpportunityApplication/, /^withdrawOpportunityApplication/, /^proposePartnerProgram/, /^listPartnerPrograms/, /^listPublicPartnerProgramsForProfile/, /^getPartnerProgram/, /^respondToPartnerProgram/, /^terminatePartnerProgram/, /^listResources/, /^getResource/, /^publishResource/, /^listMyResources/, /^recordResourceDownload/, /^listMyResourceDownloads/, /^listNetworkActivity/, /^listFollowingActivity/, /^listActivityForBusiness/, /^recordProfileView/, /^getNetworkAnalyticsDashboard/, /^listRecentProfileViewers/],
  presence: [/^fetchPresenceDraft/, /^savePresenceDraft/, /^fetchPresenceDiff/, /^createPresencePreview/, /^publishPresence/, /^unpublishPresence/, /^fetchPresenceCompleteness/, /^fetchPresenceTodayStats/, /^detectAbandonedCarts/, /^fetchPresenceCommandOverview/, /^syncPresenceActionCards/, /^fetchPresenceInsights/, /^regeneratePresenceInsights/, /^delegatePresenceInsight/, /^fetchPresenceLeads/, /^fetchPresenceOrders/, /^fetchPresenceBookings/, /^fetchPresenceOverview/, /^fetchPresenceSourcesReport/, /^fetchPresencePagesReport/, /^fetchPresenceFunnelReport/],
  commerceOps: [/^fetchProductCostProfile/, /^upsertProductCostProfile/, /^fetchDocumentTemplates/, /^createDocumentTemplate/, /^updateDocumentTemplate/, /^deleteDocumentTemplate/, /^fetchProcurementRequests/, /^createProcurementRequest/, /^updateProcurementRequest/, /^deleteProcurementRequest/],
  structure: [/^fetchStructure/],
  contentOps: [/^fetchContentRequests/, /^createContentRequest/, /^updateContentRequest/, /^deleteContentRequest/, /^approveContentRequest/, /^rejectContentRequest/],
  approvals: [/^fetchApprovals/, /^createApproval/, /^updateApproval/, /^deleteApproval/],
  assets: [/^fetchAssets/, /^createAsset/, /^updateAsset/, /^deleteAsset/],
  evidence: [/^fetchEvidence/, /^createEvidence/, /^updateEvidence/, /^deleteEvidence/],
  callTasks: [/^fetchCallTasks/, /^createCallTask/, /^updateCallTask/, /^deleteCallTask/, /^fetchCallScripts/, /^createCallScript/, /^updateCallScript/, /^deleteCallScript/],
};

const stats = Object.fromEntries(Object.keys(domains).map(d => [d, 0]));
let unassigned = [];

for (const stmt of src.statements) {
  let name = null;
  if (ts.isFunctionDeclaration(stmt) && stmt.name) name = stmt.name.text;
  else if (ts.isVariableStatement(stmt)) {
    for (const decl of stmt.declarationList.declarations) {
      if (ts.isIdentifier(decl.name)) {
        name = decl.name.text;
        break;
      }
    }
  }
  if (!name) continue;
  let assigned = false;
  for (const [d, patterns] of Object.entries(domains)) {
    if (patterns.some(p => p.test(name))) {
      stats[d]++;
      assigned = true;
      break;
    }
  }
  if (!assigned) unassigned.push(name);
}

console.log('Stats:', stats);
console.log('Unassigned count:', unassigned.length);
console.log('Unassigned sample:', unassigned.slice(0, 50));
