/**
 * KEY Cortex — Unified Event Bus (Peripheral Nervous System)
 *
 * A normalized, in-memory publish/subscribe bus that lets every organ
 * (KeyInbox, TemporalFlow, KeyGenome, StoreLink, KeyConnector, etc.)
 * emit and react to business events with a single envelope shape.
 *
 * Every published event is also persisted to the audit ledger
 * (`BusinessEvent`) so the AI has a complete trace of what happened.
 *
 * This is intentionally lightweight for Phase 1. Later phases can add
 * Redis-backed fan-out, replay, and event sourcing without changing the API.
 */

import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../core/prisma/prisma.service';
import { Optional } from '@nestjs/common';
import { CognitiveEventBusService } from './cognitive-event-bus.service';

export interface KeyCortexEvent {
  /** Unique event id (generated by the bus) */
  id: string;
  /** Organ/module that emitted the event, e.g. "key_inbox", "temporal_flow" */
  source: string;
  /** Event type, e.g. "message.received", "event.recorded" */
  type: string;
  businessId: string;
  userId?: string;
  /** Domain payload — whatever the emitter wants subscribers to know */
  payload: Record<string, unknown>;
  /** Routing/observability metadata */
  metadata?: {
    correlationId?: string;
    sessionId?: string;
    entityType?: string;
    entityId?: string;
    importance?: 'low' | 'normal' | 'high' | 'critical';
    [key: string]: unknown;
  };
  timestamp: Date;
}

export type KeyCortexEventHandler = (event: KeyCortexEvent) => Promise<void> | void;

@Injectable()
export class KeyCortexEventBusService {
  private readonly logger = new Logger(KeyCortexEventBusService.name);
  private readonly subscribers = new Map<string, Set<KeyCortexEventHandler>>();
  private readonly wildcardSubscribers = new Set<KeyCortexEventHandler>();

  constructor(
    private readonly prisma: PrismaService,
    // @Optional: the bus must keep working for consumers that do not register
    // the cognitive store. Appended, so positional construction is unaffected.
    @Optional() private readonly cognitive?: CognitiveEventBusService,
  ) {}

  /**
   * Mirror a bus event into the cognitive event store.
   *
   * Confidence defaults to 0.8 in CognitiveEventBusService; an event carrying
   * an explicit confidence in its metadata wins, since a signal that already
   * knows how sure it is should not be flattened to the default.
   */
  private async persistCognitive(event: KeyCortexEvent): Promise<void> {
    if (!this.cognitive) return;

    const declared = (event.metadata as { confidence?: unknown } | undefined)?.confidence;
    const confidence = typeof declared === 'number' ? declared : undefined;

    await this.cognitive.emit({
      businessId: event.businessId,
      sourceType: event.source,
      sourceId: event.id,
      eventType: event.type,
      payload: (event.payload ?? {}) as Record<string, unknown>,
      confidence,
    });
  }

  // ========================================================================
  // Subscribe
  // ========================================================================

  /**
   * Subscribe to a specific event type.
   * Returns an unsubscribe function.
   */
  subscribe(eventType: string, handler: KeyCortexEventHandler): () => void {
    if (!this.subscribers.has(eventType)) {
      this.subscribers.set(eventType, new Set());
    }
    this.subscribers.get(eventType)!.add(handler);
    return () => {
      this.subscribers.get(eventType)?.delete(handler);
    };
  }

  /**
   * Subscribe to all events emitted on the bus.
   */
  subscribeAll(handler: KeyCortexEventHandler): () => void {
    this.wildcardSubscribers.add(handler);
    return () => {
      this.wildcardSubscribers.delete(handler);
    };
  }

  /**
   * Subscribe to all events from a given source (e.g. all "key_inbox.*").
   */
  subscribeSource(source: string, handler: KeyCortexEventHandler): () => void {
    return this.subscribeAll((event) => {
      if (event.source === source) {
        return handler(event);
      }
    });
  }

  // ========================================================================
  // Publish
  // ========================================================================

  /**
   * Publish a normalized event to the bus and persist it to the audit ledger.
   */
  async publish(event: Omit<KeyCortexEvent, 'id' | 'timestamp'>): Promise<KeyCortexEvent> {
    const normalized: KeyCortexEvent = {
      ...event,
      id: this.generateId(),
      timestamp: new Date(),
      metadata: {
        ...(event.metadata ?? {}),
        publishedBy: 'key_cortex_event_bus',
      },
    };

    this.logger.debug(
      `[bus] ${normalized.source}/${normalized.type} → business ${normalized.businessId}`,
    );

    // Notify type-specific subscribers
    const handlers = this.subscribers.get(normalized.type);
    if (handlers) {
      for (const handler of handlers) {
        try {
          await handler(normalized);
        } catch (err: unknown) {
          this.logger.error(
            `[bus] Handler for ${normalized.type} failed: ${err instanceof Error ? err.message : String(err)}`,
          );
        }
      }
    }

    // Notify wildcard subscribers
    for (const handler of this.wildcardSubscribers) {
      try {
        await handler(normalized);
      } catch (err: unknown) {
        this.logger.error(
          `[bus] Wildcard handler failed for ${normalized.type}: ${err instanceof Error ? err.message : String(err)}`,
        );
      }
    }

    // Persist to audit ledger (non-blocking for bus throughput)
    this.persistAudit(normalized).catch((err) => {
      this.logger.warn(`[bus] Audit persist failed: ${(err as Error).message}`);
    });

    // Persist to the cognitive event store as well.
    //
    // These are two different tables for two different jobs, not a duplicate
    // write. persistAudit writes BusinessEvent — the audit ledger.
    // CognitiveEvent carries a `confidence` column BusinessEvent has no
    // equivalent for, and it is what UnifiedMemoryRetrievalService reads when
    // assembling prompt context (unified-memory-retrieval.service.ts).
    //
    // That read path was live and this table had NO writer anywhere in the
    // server, so one branch of KEY's memory fan-out returned nothing on every
    // query. This is the perception boundary every organ adapter already
    // publishes through, so it is where those rows should originate.
    //
    // Non-blocking and swallowed, exactly like the audit write: recording a
    // perception must never fail the perception.
    this.persistCognitive(normalized).catch((err) => {
      this.logger.warn(`[bus] Cognitive persist failed: ${(err as Error).message}`);
    });

    return normalized;
  }

  /**
   * Convenience method to emit an event without awaiting all handlers.
   * Useful from synchronous code paths.
   */
  emit(event: Omit<KeyCortexEvent, 'id' | 'timestamp'>): void {
    this.publish(event).catch((err) => {
      this.logger.error(`[bus] Emit failed: ${(err as Error).message}`);
    });
  }

  // ========================================================================
  // Queries (useful for tests/debugging)
  // ========================================================================

  getSubscriberCount(eventType?: string): number {
    if (eventType) {
      return this.subscribers.get(eventType)?.size ?? 0;
    }
    let total = this.wildcardSubscribers.size;
    for (const set of this.subscribers.values()) {
      total += set.size;
    }
    return total;
  }

  // ========================================================================
  // Private helpers
  // ========================================================================

  private generateId(): string {
    return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 9)}`;
  }

  private async persistAudit(event: KeyCortexEvent): Promise<void> {
    try {
      await (this.prisma.client as any).businessEvent.create({
        data: {
          businessId: event.businessId,
          eventType: event.type,
          subjectType: event.metadata?.entityType ?? 'KEY_CORTEX_EVENT',
          subjectId: event.metadata?.entityId ?? event.id,
          actorType: event.source,
          actorId: event.userId ?? 'key_cortex',
          action: 'PUBLISHED',
          after: event.payload as any,
          source: 'key_cortex_event_bus',
          // Phase 3 Skeleton: identity thread on audit ledger
          sessionId: event.metadata?.sessionId,
          commandId: (event.payload as any)?.commandId,
          correlationId: event.metadata?.correlationId,
          metadata: {
            correlationId: event.metadata?.correlationId,
            sessionId: event.metadata?.sessionId,
            importance: event.metadata?.importance ?? 'normal',
          } as any,
        },
      });
    } catch (err: unknown) {
      this.logger.error(
        `[bus] Failed to persist audit: ${err instanceof Error ? err.message : String(err)}`,
      );
      throw err;
    }
  }
}
