import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../core/prisma/prisma.service';
import { BusinessEvent, BusinessEventType } from '@prisma/client';

/**
 * KeyCortexEventService — The Heart of the Operating Kernel
 *
 * Unified business event logging system. Every action, decision, insight,
 * alert, and autonomy exercise across all KeyFlowOS modules flows through
 * this service. Events carry genome signals that feed the Business Genome
 * evolution engine.
 *
 * Design principles:
 *   1. Every significant action becomes an event (observability by default)
 *   2. Events are immutable — once logged, they cannot be changed
 *   3. Correlation IDs track multi-step workflows across services
 *   4. Genome signals mark events that should influence DNA scores
 */
@Injectable()
export class KeyCortexEventService {
  private readonly logger = new Logger(KeyCortexEventService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Log any business event. This is the core primitive — all other
   * methods are convenience wrappers around this function.
   */
  async logEvent(params: {
    businessId: string;
    type: BusinessEventType;
    module: string;
    source: string;
    action: string;
    payload: Record<string, unknown>;
    genomeSignal?: boolean;
    genomeImpact?: number;
    userId?: string;
    sessionId?: string;
    correlationId?: string;
    parentEventId?: string;
  }): Promise<BusinessEvent> {
    const event = await this.prisma.client.businessEvent.create({
      data: { ...params, createdAt: new Date() },
    });
    this.logger.debug(
      `[Event] ${params.source}/${params.module}: ${params.action}`,
    );
    return event;
  }

  /**
   * Log an action execution — the most common event type.
   * Captures parameters, result, and execution time for performance tracking.
   */
  async logActionExecuted(
    businessId: string,
    params: {
      module: string;
      source: string;
      action: string;
      parameters: Record<string, unknown>;
      result: 'success' | 'error';
      executionTimeMs: number;
      correlationId?: string;
      userId?: string;
    },
  ): Promise<BusinessEvent> {
    return this.logEvent({
      businessId,
      type: BusinessEventType.ACTION_EXECUTED,
      module: params.module,
      source: params.source,
      action: params.action,
      payload: {
        parameters: params.parameters,
        result: params.result,
        executionTimeMs: params.executionTimeMs,
      },
      correlationId: params.correlationId,
      userId: params.userId,
    });
  }

  /**
   * Log a decision made by KEY Cortex, autopilot, or the delegation loop.
   * Decisions are always marked as genome signals since they represent
   * autonomous reasoning that should influence DNA evolution.
   */
  async logDecision(
    businessId: string,
    params: {
      decision: string;
      rationale: string;
      confidence: number;
      source: string;
      correlationId?: string;
      genomeSignal?: boolean;
    },
  ): Promise<BusinessEvent> {
    return this.logEvent({
      businessId,
      type: BusinessEventType.DECISION_MADE,
      module: 'key_cortex',
      source: params.source,
      action: 'decision',
      payload: {
        decision: params.decision,
        rationale: params.rationale,
        confidence: params.confidence,
      },
      correlationId: params.correlationId,
      genomeSignal: params.genomeSignal ?? true,
    });
  }

  /**
   * Log a recommendation — either offered to the user or acted upon.
   * When acted=true, the event type becomes RECOMMENDATION_ACTED which
   * is a strong positive signal for genome evolution.
   */
  async logRecommendation(
    businessId: string,
    params: {
      recommendation: string;
      category: string;
      confidence: number;
      estimatedImpact?: Record<string, unknown>;
      acted?: boolean;
      correlationId?: string;
      userId?: string;
    },
  ): Promise<BusinessEvent> {
    return this.logEvent({
      businessId,
      type: params.acted
        ? BusinessEventType.RECOMMENDATION_ACTED
        : BusinessEventType.RECOMMENDATION_OFFERED,
      module: 'key_cortex',
      source: 'key_cortex',
      action: 'recommend',
      payload: {
        recommendation: params.recommendation,
        category: params.category,
        confidence: params.confidence,
        estimatedImpact: params.estimatedImpact,
      },
      correlationId: params.correlationId,
      userId: params.userId,
    });
  }

  /**
   * Log an insight generated by the KEY Cortex insight engine.
   * Insights are genome signals because they represent new understanding
   * about the business that should influence DNA scores.
   */
  async logInsight(
    businessId: string,
    params: {
      insight: string;
      category: string;
      confidence: number;
      details?: Record<string, unknown>;
      correlationId?: string;
    },
  ): Promise<BusinessEvent> {
    return this.logEvent({
      businessId,
      type: BusinessEventType.INSIGHT_GENERATED,
      module: 'key_cortex',
      source: 'key_cortex',
      action: 'insight',
      payload: {
        insight: params.insight,
        category: params.category,
        confidence: params.confidence,
        details: params.details,
      },
      correlationId: params.correlationId,
      genomeSignal: true,
    });
  }

  /**
   * Log an alert triggered by the system, autopilot monitor, or governance.
   */
  async logAlert(
    businessId: string,
    params: {
      alert: string;
      severity: 'low' | 'medium' | 'high' | 'critical';
      module: string;
      source: string;
      details?: Record<string, unknown>;
      correlationId?: string;
    },
  ): Promise<BusinessEvent> {
    return this.logEvent({
      businessId,
      type: BusinessEventType.ALERT_TRIGGERED,
      module: params.module,
      source: params.source,
      action: 'alert',
      payload: {
        alert: params.alert,
        severity: params.severity,
        details: params.details,
      },
      correlationId: params.correlationId,
      genomeSignal: params.severity === 'high' || params.severity === 'critical',
    });
  }

  /**
   * Log autonomy being exercised — when KEY Cortex or autopilot takes
   * action without human approval. This is a critical genome signal.
   */
  async logAutonomy(
    businessId: string,
    params: {
      action: string;
      module: string;
      result: 'success' | 'error' | 'partial';
      approvalRequired: boolean;
      details?: Record<string, unknown>;
      correlationId?: string;
    },
  ): Promise<BusinessEvent> {
    return this.logEvent({
      businessId,
      type: BusinessEventType.AUTONOMY_EXERCISED,
      module: params.module,
      source: 'autopilot',
      action: params.action,
      payload: {
        result: params.result,
        approvalRequired: params.approvalRequired,
        details: params.details,
      },
      correlationId: params.correlationId,
      genomeSignal: true,
    });
  }

  /**
   * Log a governance decision — when the delegation loop or governance
   * system changes autonomy settings, approval thresholds, etc.
   */
  async logGovernance(
    businessId: string,
    params: {
      decision: string;
      previousState: Record<string, unknown>;
      newState: Record<string, unknown>;
      decidedBy: string;
      correlationId?: string;
    },
  ): Promise<BusinessEvent> {
    return this.logEvent({
      businessId,
      type: BusinessEventType.GOVERNANCE_DECISION,
      module: 'key_cortex',
      source: 'delegation_loop',
      action: 'governance',
      payload: {
        decision: params.decision,
        previousState: params.previousState,
        newState: params.newState,
        decidedBy: params.decidedBy,
      },
      correlationId: params.correlationId,
      genomeSignal: true,
    });
  }

  /**
   * Log a genome evolution event — when DNA scores change based on
   * accumulated signals. This closes the feedback loop.
   */
  async logGenomeEvolution(
    businessId: string,
    params: {
      section: string;
      previousScore: number;
      newScore: number;
      signals: string[];
      correlationId?: string;
    },
  ): Promise<BusinessEvent> {
    return this.logEvent({
      businessId,
      type: BusinessEventType.GENOME_EVOLUTION,
      module: 'genome',
      source: 'genome_engine',
      action: 'evolve',
      payload: {
        section: params.section,
        previousScore: params.previousScore,
        newScore: params.newScore,
        signals: params.signals,
      },
      correlationId: params.correlationId,
      genomeSignal: true,
      genomeImpact: params.newScore - params.previousScore,
    });
  }

  /**
   * Query events with flexible filtering.
   */
  async getEvents(
    businessId: string,
    filters: {
      type?: BusinessEventType;
      module?: string;
      source?: string;
      startDate?: Date;
      endDate?: Date;
      genomeSignal?: boolean;
      limit?: number;
      offset?: number;
    } = {},
  ): Promise<BusinessEvent[]> {
    return this.prisma.client.businessEvent.findMany({
      where: { businessId, ...filters },
      orderBy: { createdAt: 'desc' },
      take: filters.limit ?? 100,
      skip: filters.offset ?? 0,
    });
  }

  /**
   * Get the full event chain for a correlation ID.
   * Used to trace multi-step workflows across services.
   */
  async getEventChain(correlationId: string): Promise<BusinessEvent[]> {
    return this.prisma.client.businessEvent.findMany({
      where: { correlationId },
      orderBy: { createdAt: 'asc' },
    });
  }

  /**
   * Get event statistics grouped by type for a time period.
   * Used by dashboards and the genome engine.
   */
  async getEventStats(
    businessId: string,
    period: 'day' | 'week' | 'month',
  ): Promise<Record<string, number>> {
    const start = new Date();
    if (period === 'day') start.setDate(start.getDate() - 1);
    else if (period === 'week') start.setDate(start.getDate() - 7);
    else start.setMonth(start.getMonth() - 1);

    const events = await this.prisma.client.businessEvent.groupBy({
      by: ['type'],
      where: { businessId, createdAt: { gte: start } },
      _count: true,
    });

    return Object.fromEntries(events.map((e) => [e.type, e._count]));
  }

  /**
   * Get the most recent genome signals for a business.
   * Used by the genome engine to process signal accumulation.
   */
  async getGenomeSignals(
    businessId: string,
    limit = 100,
  ): Promise<BusinessEvent[]> {
    return this.prisma.client.businessEvent.findMany({
      where: { businessId, genomeSignal: true },
      orderBy: { createdAt: 'desc' },
      take: limit,
    });
  }

  /**
   * Get events for a specific module within a time range.
   * Useful for module-specific audit logs.
   */
  async getModuleEvents(
    businessId: string,
    module: string,
    options: {
      startDate?: Date;
      endDate?: Date;
      limit?: number;
      offset?: number;
    } = {},
  ): Promise<BusinessEvent[]> {
    const where: Record<string, unknown> = { businessId, module };
    if (options.startDate || options.endDate) {
      where.createdAt = {};
      if (options.startDate) (where.createdAt as Record<string, Date>).gte = options.startDate;
      if (options.endDate) (where.createdAt as Record<string, Date>).lte = options.endDate;
    }
    return this.prisma.client.businessEvent.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      take: options.limit ?? 100,
      skip: options.offset ?? 0,
    });
  }
}
